### ISSUE TITLE
Azure Identity => ERROR in getToken() 

### ISSUE THREAD

**Issue by sstilos** [microsoftgraph/msgraph-sdk-java#817] opened 2021-07-05 16:34 UTC
Hello, 

I am using the following functionality (copied from [here](https://docs.microsoft.com/en-us/graph/api/user-sendmail?view=graph-rest-1.0&tabs=java)) in order to send a simple email to my account, but I receive the authentication error that you can find below :

 
    public void sendEmail() throws MessagingException, IOException {

	  String applicationId = ".....";
	  String tenantId = "....";
	  String authenticationKey = "....";
	
	  ClientSecretCredential clientSecretCredential = new ClientSecretCredentialBuilder()
			.clientId(applicationId)
			.clientSecret(authenticationKey)
			.tenantId(tenantId)
			.build();

	  List<String> scopes = Arrays.asList("https://graph.microsoft.com/.default");
	  TokenCredentialAuthProvider tokenCredentialAuthProvider = new TokenCredentialAuthProvider(scopes, clientSecretCredential);

	  GraphServiceClient graphClient = GraphServiceClient
					.builder()
					.authenticationProvider(tokenCredentialAuthProvider)
					.buildClient();

	  Message message = new Message();
	  message.subject = "test subject";
	  ItemBody body = new ItemBody();
	  body.contentType = BodyType.TEXT;
	  body.content = "test content";
	  message.body = body;

	  LinkedList<Recipient> toRecipientsList = new LinkedList<Recipient>();
	  Recipient toRecipients = new Recipient();
	  EmailAddress emailAddress = new EmailAddress();
	  emailAddress.address = "........";
	  toRecipients.emailAddress = emailAddress;
	  toRecipientsList.add(toRecipients);
	  message.toRecipients = toRecipientsList;

	  graphClient.me()
			.sendMail(UserSendMailParameterSet
					.newBuilder()
					.withMessage(message)
					.withSaveToSentItems(false)
					.build())
			.buildRequest()
			.post();
    }

having the following dependencies : 

	       <dependency>
	                <groupId>com.nimbusds</groupId>
			<artifactId>oauth2-oidc-sdk</artifactId>
			<version>6.5</version>
		</dependency>
		<dependency>
			<groupId>com.microsoft.azure</groupId>
			<artifactId>msal4j</artifactId>
			<version>1.10.0</version>
		</dependency>
		<dependency>
			<groupId>com.microsoft.graph</groupId>
			<artifactId>microsoft-graph-auth</artifactId>
			<version>0.3.0</version>
		</dependency>
		<dependency>
			
			<groupId>com.microsoft.graph</groupId>
			<artifactId>microsoft-graph</artifactId>
			<version>3.3.0</version>
		</dependency>
		<dependency>
			<groupId>com.azure</groupId>
			<artifactId>azure-identity</artifactId>
			<version>1.3.0</version>
		</dependency>
		<dependency>
			<groupId>com.microsoft.graph</groupId>
			<artifactId>microsoft-graph-core</artifactId>
			<version>2.0.4</version>
		</dependency>

The error logs are the following ones : 

```
021-06-18_13:55:01.747 ERROR c.a.identity.ClientSecretCredential - Azure Identity => ERROR in getToken() call for scopes [https://graph.microsoft.com/.default]: A request was made to load the default HttpClient provider but one could not be found on the classpath. If you are using a dependency manager, consider including a dependency on azure-core-http-netty or azure-core-http-okhttp. Depending on your existing dependencies, you have the choice of Netty or OkHttp implementations. Additionally, refer to https://aka.ms/azsdk/java/docs/custom-httpclient to learn about writing your own implementation.
2021-06-18_13:55:01.759 ERROR o.a.c.c.C.[.[.[.[dispatcherServlet] - Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is com.microsoft.graph.core.ClientException: Error executing the request] with root cause
java.lang.IllegalStateException: A request was made to load the default HttpClient provider but one could not be found on the classpath. If you are using a dependency manager, consider including a dependency on azure-core-http-netty or azure-core-http-okhttp. Depending on your existing dependencies, you have the choice of Netty or OkHttp implementations. Additionally, refer to https://aka.ms/azsdk/java/docs/custom-httpclient to learn about writing your own implementation.
	at com.azure.core.implementation.http.HttpClientProviders.createInstance(HttpClientProviders.java:51)
	at com.azure.core.http.HttpClient.createDefault(HttpClient.java:50)
	at com.azure.core.http.HttpClient.createDefault(HttpClient.java:40)
	at com.azure.identity.implementation.IdentityClient.initializeHttpPipelineAdapter(IdentityClient.java:1291)
	at com.azure.identity.implementation.IdentityClient.lambda$getConfidentialClientApplication$3(IdentityClient.java:219)
	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:44)
	at reactor.core.publisher.MonoCacheTime.subscribeOrReturn(MonoCacheTime.java:132)
	at reactor.core.publisher.Mono.subscribe(Mono.java:4203)
	at reactor.core.publisher.Mono.subscribeWith(Mono.java:4329)
	at reactor.core.publisher.Mono.toFuture(Mono.java:4663)
	at com.microsoft.graph.authentication.TokenCredentialAuthProvider.getAuthorizationTokenAsync(TokenCredentialAuthProvider.java:58)
	at com.microsoft.graph.httpcore.AuthenticationHandler.intercept(AuthenticationHandler.java:54)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
	at com.microsoft.graph.httpcore.TelemetryHandler.intercept(TelemetryHandler.java:69)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:229)
	at okhttp3.RealCall.execute(RealCall.java:81)
	at com.microsoft.graph.http.CoreHttpProvider.sendRequestInternal(CoreHttpProvider.java:395)
	at com.microsoft.graph.http.CoreHttpProvider.send(CoreHttpProvider.java:222)
	at com.microsoft.graph.http.CoreHttpProvider.send(CoreHttpProvider.java:199)
	at com.microsoft.graph.http.BaseRequest.send(BaseRequest.java:332)
	at com.microsoft.graph.requests.UserSendMailRequest.post(UserSendMailRequest.java:54)
	at org.protera.flexbridge.services.EmailService.sendEmail2(EmailService.java:183)
	at org.protera.flexbridge.services.NotificationMsController.sendRegistrationRequestEmailtoUser(NotificationMsController.java:144)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:105)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:879)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:793)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1040)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:634)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:373)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1590)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:834)
```
Could someone please advise on that issue? 
[AB#10128](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/10128)

**Comment by baywet** [comment] 2021-07-05 16:43
Hi @sstilos 
Thanks for reaching out.
Can you try with the library version 3.9.0, the core sdk version 2.0.7, azure identity 1.3.1 and remove msal4j please?
Thanks.

**Comment by sstilos** [comment] 2021-07-06 10:48
Hi @baywet,
Thanks for your prompt response!
I updated the dependencies based on your suggestions, but I receive again an identical error :

```
2021-07-06_13:46:25.453 ERROR c.a.identity.ClientSecretCredential - Azure Identity => ERROR in getToken() call for scopes [https://graph.microsoft.com/.default]: io/netty/channel/unix/DomainSocketAddress
2021-07-06_13:46:25.464 ERROR o.a.c.c.C.[.[.[.[dispatcherServlet] - Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is com.microsoft.graph.core.ClientException: Error executing the request] with root cause
java.lang.NoClassDefFoundError: io/netty/channel/unix/DomainSocketAddress
	at reactor.netty.http.client.UriEndpoint.toExternalForm(UriEndpoint.java:65)
	at reactor.netty.http.client.HttpClientConnect$HttpClientHandler.<init>(HttpClientConnect.java:494)
	at reactor.netty.http.client.HttpClientConnect$MonoHttpConnect.subscribe(HttpClientConnect.java:208)
	at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64)
	at reactor.core.publisher.FluxRetryWhen.subscribe(FluxRetryWhen.java:79)
	at reactor.core.publisher.MonoRetryWhen.subscribeOrReturn(MonoRetryWhen.java:46)
	at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:57)
	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)
	at reactor.core.publisher.Mono.subscribe(Mono.java:4218)
	at reactor.core.publisher.Mono.block(Mono.java:1677)
	at com.azure.identity.implementation.HttpPipelineAdapter.send(HttpPipelineAdapter.java:58)
	at com.microsoft.aad.msal4j.HttpHelper.executeHttpRequestWithRetries(HttpHelper.java:86)
	at com.microsoft.aad.msal4j.HttpHelper.executeHttpRequest(HttpHelper.java:64)
	at com.microsoft.aad.msal4j.AadInstanceDiscoveryProvider.httpRequest(AadInstanceDiscoveryProvider.java:175)
	at com.microsoft.aad.msal4j.AadInstanceDiscoveryProvider.sendInstanceDiscoveryRequest(AadInstanceDiscoveryProvider.java:157)
	at com.microsoft.aad.msal4j.AadInstanceDiscoveryProvider.doInstanceDiscoveryAndCache(AadInstanceDiscoveryProvider.java:221)
	at com.microsoft.aad.msal4j.AadInstanceDiscoveryProvider.getMetadataEntry(AadInstanceDiscoveryProvider.java:56)
	at com.microsoft.aad.msal4j.AuthenticationResultSupplier.getAuthorityWithPrefNetworkHost(AuthenticationResultSupplier.java:32)
	at com.microsoft.aad.msal4j.AcquireTokenSilentSupplier.execute(AcquireTokenSilentSupplier.java:23)
	at com.microsoft.aad.msal4j.AcquireTokenByClientCredentialSupplier.execute(AcquireTokenByClientCredentialSupplier.java:41)
	at com.microsoft.aad.msal4j.AuthenticationResultSupplier.get(AuthenticationResultSupplier.java:59)
	at com.microsoft.aad.msal4j.AuthenticationResultSupplier.get(AuthenticationResultSupplier.java:17)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run$$$capture(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1692)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
```

**Comment by baywet** [comment] 2021-07-06 12:23
It looks like it's missing the [DomainSocketAddress](https://netty.io/4.0/api/io/netty/channel/unix/DomainSocketAddress.html) class which looks like it's part of [this package](https://mvnrepository.com/artifact/io.netty/netty-transport-native-unix-common/4.1.65.Final) (but I'm not sure). Maybe try to add it to your project configuration? If this doesn't work, maybe try to [add the all package instead](https://mvnrepository.com/artifact/io.netty/netty-all/4.1.65.Final)

**Comment by sstilos** [comment] 2021-07-07 11:23
Hi @baywet,

I made many tests with various dependencies and versions, but I continue receiving error messages. Do you maybe know if there is a specific dependencies-versions combination for which, the relevant code ([link](https://docs.microsoft.com/en-us/graph/api/user-sendmail?view=graph-rest-1.0&tabs=java)) works as expected?

**Comment by baywet** [comment] 2021-07-07 12:05
Thanks for the additional details. Last test to confirm where the error might be coming from:
Can you add the following line before the GraphClient creation, remove the line sending the message and see whether you get the same error please?
```Java
tokenCredentialAuthProvider.getAuthorizationTokenAsync(new URL("https://graph.microsoft.com")).get();
```

Thanks!

**Comment by sstilos** [comment] 2021-07-07 13:39
I added that line and the errors that I receive (based on the dependencies-versions I add/remove) are identical.

**Comment by baywet** [comment] 2021-07-07 15:41
thanks for confirming this!
As the issue is coming from msal for java (via azure identity, which is a dependency of this SDK), I suggest you [reach out](https://github.com/AzureAD/microsoft-authentication-library-for-java/issues/new) directly to this team to get better support.
Closing.

**Closed by baywet** 2021-07-07 15:41 UTC
Labels: Needs: Attention :wave:, question

**Comment by zaynutdinovz** [comment] 2023-02-07 04:27
I am getting the same issue when I try to authorize with the certificate
