### ISSUE TITLE
GraphServiceException - delta(token) returns an invalid URL

### ISSUE THREAD

**Issue by albertomatos80** [microsoftgraph/msgraph-sdk-java#89] opened 2018-05-04 13:25 UTC
The code `client.me().drive().root().delta({token}).buildRequest().get()` returns an invalid URL.

### Expected behavior

URL
```
https://graph.microsoft.com/beta/me/drive/root/delta?token={token}
```
Return
```
{
    "@odata.context": "https://graph.microsoft.com/beta/$metadata#Collection(driveItem)",
    "@odata.deltaLink": "https://graph.microsoft.com/beta/me/drive/root/delta?token={token}",
    "value": []
}
```

### Actual behavior

URL
```
https://graph.microsoft.com/beta/me/drive/root/microsoft.graph.delta(token='{token}')
```
Return
```
{
    "error": {
        "code": "invalidRequest",
        "message": "Invalid API or resource",
        "innerError": {
            "request-id": "143b283c-7db0-47e3-9859-4767fbc8933f",
            "date": "2018-05-04T13:04:29"
        }
    }
}

com.microsoft.graph.http.GraphServiceException: GET https://graph.microsoft.com/v1.0/me/drive/root/microsoft.graph.delta(token='{token}')

SdkVersion : graph-java-v0.2.0

GRAVE: Throwable detail: com.microsoft.graph.http.GraphServiceException: GET https://graph.microsoft.com/v1.0/me/drive/root/microsoft.graph.delta(token='{token}')
```
This way works:
```
List<Option> options = new LinkedList<>();
options.add(new QueryOption("token", {token}));

IDriveItemDeltaCollectionPage deltaPage = client.me().drive().root().delta().buildRequest(options).get();
```
### Steps to reproduce the behavior

You can reproduce the error in Graph Explorer:
`https://developer.microsoft.com/en-us/graph/graph-explorer`

**Comment by bullsseye** [comment] 2018-07-10 04:19
I am not able to reproduce this issue. I am getting the required url in the delta response

**Comment by deepak2016** [comment] 2018-07-12 10:20
Closing this issue as it is not reproducible. If you face this issue, kindly reopen the same. Thanks

**Closed by deepak2016** 2018-07-12 10:20 UTC
Labels: tracked

**Comment by alien0matic** [comment] 2018-11-15 16:08
I have exactly the same problem as the op.
Is there any way I can help you reproduce or fix this?

PS: The request URL looks like it is mentioned here under Example (Last page in a set). https://docs.microsoft.com/de-de/onedrive/developer/rest-api/api/driveitem_delta?view=odsp-graph-online
There are 3 different types of how the URL should look like in the page and the only one working is the one mentioned by op.

**Comment by av1ctor** [comment] 2020-06-17 21:25
Same error as op. 

Tested in Graph Explorer and it shows the same error if that /microsoft.graph.delta(token='{token}') style is used, instead of the /delta?token={token} one.

Perhaps it depends on the drive type.. A personal account was used to test, not a business one.

**Comment by ng-marcus** [comment] 2020-09-11 10:12
A little late to a 2 year old closed ticket, but I see the same on a business drive, the initial URL returned on a delta query after paging through some nextLinks has the delta(token='{token}') format.  If I then call again starting with the delta URL n query options for the request, it return the delta token in the expected delta?token={token} format
