### ISSUE TITLE
ClassCastException on get calendars and calendar view request with java client

### ISSUE THREAD

**Issue by megicivovic** [microsoftgraph/msgraph-sdk-java#635] opened 2021-01-30 18:57 UTC
### Expected behavior
microsoft-graph client version 1.6.0
https://docs.microsoft.com/en-us/graph/api/user-list-calendarview?view=graph-rest-beta&tabs=java

```
      iEventCollectionNextPage =
          graphServiceClient
              .me()
              .calendars()
              .byId(doodleCalendar.getProviderId())
              .calendarView()
              .buildRequest(requestOptions)
              .get();
```
to return a valid IEventCollectionNextPage object

and similar thing happens for `CalendarCollectionRequest.get`

### Actual behavior

`java.lang.ClassCastException: class java.io.BufferedInputStream cannot be cast to class com.microsoft.graph.requests.extensions.EventCollectionResponse (java.io.BufferedInputStream is in module java.base of loader 'bootstrap'; com.microsoft.graph.requests.extensions.EventCollectionResponse is in unnamed module of loader org.springframework.boot.loader.LaunchedURLClassLoader @5034c75a)
    at com.microsoft.graph.requests.extensions.EventCollectionRequest.get(EventCollectionRequest.java:52)`

and 

`java.lang.ClassCastException: class java.io.BufferedInputStream cannot be cast to class com.microsoft.graph.requests.extensions.CalendarCollectionResponse (java.io.BufferedInputStream is in module java.base of loader 'bootstrap'; com.microsoft.graph.requests.extensions.CalendarCollectionResponse is in unnamed module of loader org.springframework.boot.loader.LaunchedURLClassLoader @5034c75a)
    at com.microsoft.graph.requests.extensions.CalendarCollectionRequest.get(CalendarCollectionRequest.java:52)`

### Steps to reproduce the behavior
just try to execute the mentioned api call using a Java client

 
[AB#7898](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7898)

**Comment by baywet** [comment] 2021-02-01 13:27
Hi @megicivovic 
Thanks for reaching out.
Can you upgrade to version 2.6.0 and see if you still have the issue.
The version your application is using is quite old, we've fixed a large number of bugs and made improvements since.
Thanks!

**Comment by gantners** [comment] 2021-02-02 07:56
Hi!
Since Saturday 30.01.2021 02:40 i do get the same error messages sporadically on 1.9.0 for multiple actions on multiple clients.

` class java.io.BufferedInputStream cannot be cast to class com.microsoft.graph.requests.extensions.MessageCollectionResponse (java.io.BufferedInputStream is in module java.base of loader 'bootstrap'; com.microsoft.graph.requests.extensions.MessageCollectionResponse is in unnamed module of loader 'app')`

Also when I'm trying to draft a message.

`getClient().me().messages().buildRequest().post(m);`

`java.lang.ClassCastException: class java.io.BufferedInputStream cannot be cast to class com.microsoft.graph.models.extensions.Message (java.io.BufferedInputStream is in module java.base of loader 'bootstrap'; com.microsoft.graph.models.extensions.Message is in unnamed module of loader 'app')
`

`
at com.microsoft.graph.requests.extensions.MessageRequest.post(MessageRequest.java:127)
at com.microsoft.graph.requests.extensions.MessageCollectionRequest.post(MessageCollectionRequest.java:67)
`

Has there been a change recently on the serverside which could lead to those messages?
I will upgrade as well, test and let you know.

**Comment by megicivovic** [comment] 2021-02-02 08:11
@baywet , I've upgraded to 2.6.0 and this seems to have fixed the issue. No errors since yesterday.

**Comment by baywet** [comment] 2021-02-02 13:28
@megicivovic thanks for letting us know, glad it worked.
@gantners I'm not aware of any service change at the moment, so I'm not sure why something that was in production and working for a while would suddenly start acting up.
I'm going to close this issue for now assuming the upgrade will fix it as well on your end. Please leave a comment if it's not the case, I'll reopen it.

**Closed by baywet** 2021-02-02 13:28 UTC
Labels: Needs: Attention :wave:, question

**Comment by megicivovic** [comment] 2021-02-02 15:27
@baywet , but now we are seeing this error `ex-lm=Error during http request","ex":"com.microsoft.graph.core.ClientException: Error during http request\n\tat com.microsoft.graph.http.CoreHttpProvider.sendRequestInternal(CoreHttpProvider.java:471)\n\tat com.microsoft.graph.http.CoreHttpProvider.send(CoreHttpProvider.java:220)\n\tat com.microsoft.graph.http.CoreHttpProvider.send(CoreHttpProvider.java:200)\n\tat com.microsoft.graph.http.BaseCollectionRequest.send(BaseCollectionRequest.java:92)\n\tat com.microsoft.graph.requests.extensions.EventCollectionRequest.get(EventCollectionRequest.java:61)\n\tat com.doodle.calendarprovider.provider.outlook.OutlookService.getSchedule(OutlookService.java:267)\n\tat com.doodle.calendarprovider.provider.outlook.OutlookService$$FastClassBySpringCGLIB$$956be8ef.invoke(<generated>)\n\tat org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)\n\tat org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:771)\n\tat org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)\n\tat org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)\n\tat org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:88)\n\tat com.doodle.calendarprovider.provider.ProviderServiceAdvisor.mapException(ProviderServiceAdvisor.java:33)\n\tat jdk.internal.reflect.GeneratedMethodAccessor159.invoke(Unknown Source)\n\tat java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n\tat java.base/java.lang.reflect.Method.invoke(Method.java:566)\n\tat org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:644)\n\tat org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:633)\n\tat org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:70)\n\tat org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:175)\n\tat org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)\n\tat org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:88)\n\tat com.doodle.calendarprovider.config.UserDomainAspectConfig.process(UserDomainAspectConfig.java:84)\n\tat jdk.internal.reflect.GeneratedMethodAccessor158.invoke(Unknown Source)\n\tat java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n\tat java.base/java.lang.reflect.Method.invoke(Method.java:566)\n\tat org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:644)\n\tat org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:633)\n\tat org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:70)\n\tat org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:175)\n\tat org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)\n\tat org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:95)\n\tat org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)\n\tat org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)\n\tat org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:691)\n\tat com.doodle.calendarprovider.provider.outlook.OutlookService$$EnhancerBySpringCGLIB$$8691eb60.getSchedule(<generated>)\n\tat com.doodle.calendarprovider.service.AvailabilityService.getEvents(AvailabilityService.java:194)\n\tat com.doodle.calendarprovider.service.AvailabilityService.lambda$getEventsWrapper$5(AvailabilityService.java:176)\n\tat java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)\n\tat java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)\n\tat java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)\n\tat java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)\n\tat java.base/java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:290)\n\tat java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:746)\n\tat java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)\n\tat java.base/java.util.concurrent.ForkJoinTask.doInvoke(ForkJoinTask.java:408)\n\tat java.base/java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:736)\n\tat java.base/java.util.stream.ForEachOps$ForEachOp.evaluateParallel(ForEachOps.java:159)\n\tat java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(ForEachOps.java:173)\n\tat java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)\n\tat java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)\n\tat com.doodle.calendarprovider.service.AvailabilityService.lambda$getEventsWrapper$6(AvailabilityService.java:172)\n\tat java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1407)\n\tat java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)\n\tat java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)\n\tat java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)\n\tat java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)\n\tat java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)\nCaused by: java.net.SocketTimeoutException: timeout\n\tat okio.Okio$4.newTimeoutException(Okio.java:232)\n\tat okio.AsyncTimeout.exit(AsyncTimeout.java:285)\n\tat okio.AsyncTimeout$2.read(AsyncTimeout.java:241)\n\tat okio.RealBufferedSource.indexOf(RealBufferedSource.java:354)\n\tat okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:226)\n\tat okhttp3.internal.http1.Http1Codec.readHeaderLine(Http1Codec.java:215)\n\tat okhttp3.internal.http1.Http1Codec.readResponseHeaders(Http1Codec.java:189)\n\tat okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:88)\n\tat okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)\n\tat okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)\n\tat okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)\n\tat okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)\n\tat okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)\n\tat okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)\n\tat okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)\n\tat okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)\n\tat okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)\n\tat okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126)\n\tat okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)\n\tat okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)\n\tat com.microsoft.graph.httpcore.RedirectHandler.intercept(RedirectHandler.java:123)\n\tat okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)\n\tat okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)\n\tat com.microsoft.graph.httpcore.RetryHandler.intercept(RetryHandler.java:140)\n\tat okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)\n\tat okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)\n\tat com.microsoft.graph.httpcore.AuthenticationHandler.intercept(AuthenticationHandler.java:31)\n\tat okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)\n\tat okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)\n\tat com.microsoft.graph.httpcore.TelemetryHandler.intercept(TelemetryHandler.java:43)\n\tat okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)\n\tat okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)\n\tat okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:254)\n\tat okhttp3.RealCall.execute(RealCall.java:92)\n\tat com.microsoft.graph.http.CoreHttpProvider.sendRequestInternal(CoreHttpProvider.java:398)\n\t... 57 common frames omitted\nCaused by: javax.net.ssl.SSLException: Socket closed\n\tat java.base/sun.security.ssl.Alert.createSSLException(Alert.java:127)\n\tat java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:349)\n\tat java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:292)\n\tat java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:287)\n\tat java.base/sun.security.ssl.SSLSocketImpl.handleException(SSLSocketImpl.java:1581)\n\tat java.base/sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:979)\n\tat okio.Okio$2.read(Okio.java:140)\n\tat okio.AsyncTimeout$2.read(AsyncTimeout.java:237)\n\t... 89 common frames omitted\nCaused by: java.net.SocketException: Socket closed\n\tat java.base/java.net.SocketInputStream.read(SocketInputStream.java:183)\n\tat java.base/java.net.SocketInputStream.read(SocketInputStream.java:140)\n\tat java.base/sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:478)\n\tat java.base/sun.security.ssl.SSLSocketInputRecord.readHeader(SSLSocketInputRecord.java:472)\n\tat java.base/sun.security.ssl.SSLSocketInputRecord.bytesInCompletePacket(SSLSocketInputRecord.java:70)\n\tat java.base/sun.security.ssl.SSLSocketImpl.readApplicationRecord(SSLSocketImpl.java:1354)\n\tat java.base/sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:963)\n\t... 91 common frames omitted\n"}`

**Comment by megicivovic** [comment] 2021-02-02 15:32
Maybe it is the issue described here https://github.com/microsoftgraph/msgraph-sdk-java/issues/553

**Comment by baywet** [comment] 2021-02-02 15:39
@megicivovic it looks a lot like #553 indeed.
Can you make sure you read up [this comment](https://github.com/microsoftgraph/msgraph-sdk-java/issues/553#issuecomment-735830313), investigate the different options I'm suggesting and report your findings there please?

**Comment by baywet** [comment] 2021-02-02 15:41
also, make sure you're using core 1.0.7 (latest), a number of improvements have been made in connection management to reduce occurrences of that error.

**Comment by baywet** [comment] 2021-02-03 13:49
additionally, it looks like the original problem of this issue (invalid cast) is not solved by a newer version. To avoid duplication and because the community has been active on the other issue, I'll follow up on the original problem on #641

**Comment by gantners** [comment] 2021-02-05 13:17
Confirmed, after upgrading to 2.6.0, ClassCastExceptions do not show up anymore.
