### ISSUE TITLE
Error code: ErrorQuotaExceeded with message "Cannot get ID from name."

### ISSUE THREAD

**Issue by mekaramr** [microsoftgraph/msgraph-sdk-java#767] opened 2021-05-18 16:47 UTC
Dear Team,
I am using below code to set the SingleValueLegacyExtendedProperty in java with graph version 3.1.0, I am getting the error says
com.microsoft.graph.http.GraphServiceException: Error code: ErrorQuotaExceeded
Error message: Cannot get ID from name.
PATCH https://graph.microsoft.com/v1.0/users/{emailId}/messages/AAMkADIzOTk0ZGE0LTM3NDMtNDVmNC1hMDI1LWNhZjhlYTY4NzYyZABGAAAAAADNi3vV7r2rQZhnzEtDpBVbBwBuk9kw84y_Q5iZ3kzrhAWXAAAAAAEPAABuk9kw84y_Q5iZ3kzrhAWXAAAnZOYJAAA=
SdkVersion : graph-java/v3.1.0
[...]
403 : Forbidden
Below is the code used, kindly help me in finding the issue.
SingleValueLegacyExtendedPropertyCollectionResponse response = new SingleValueLegacyExtendedPropertyCollectionResponse();
SingleValueLegacyExtendedProperty property = new SingleValueLegacyExtendedProperty();
property.id = "String " + UUID.randomUUID().toString() + " Name " + "UpdateEmailUUID";
property.value = SINGLE_EXTENDED_PROPERTY_VALUE;
response.value = Arrays.asList(property);
SingleValueLegacyExtendedPropertyCollectionRequestBuilder builder
= new SingleValueLegacyExtendedPropertyCollectionRequestBuilder("", graphClient, null);
SingleValueLegacyExtendedPropertyCollectionPage collectionPage = new SingleValueLegacyExtendedPropertyCollectionPage(response, builder);
message.singleValueExtendedProperties = collectionPage;

I wanted to understand the issue here, what is the meaning of Error code: ErrorQuotaExceeded with message "Cannot get ID from name."
Kindly help me in this issue
 
[AB#9502](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/9502)

**Comment by baywet** [comment] 2021-05-19 11:27
Closing as duplicate of #764

**Closed by baywet** 2021-05-19 11:27 UTC
