### ISSUE TITLE
com.microsoft.graph.models.Call serailization exception with "Dangling name: applicationInstance"

### ISSUE THREAD

**Issue by devillaccc** [microsoftgraph/msgraph-sdk-java#1969] opened 2024-04-28 11:43 UTC
### Expected behavior
Serialization of Call object to initiate a PSTN call using Bot

https://learn.microsoft.com/en-us/graph/api/application-post-calls?view=graph-rest-1.0&tabs=java#example-9-create-peer-to-peer-pstn-call-with-service-hosted-media

graph: v6.7.0
microsoft-graph-core: 3.1.9
bot schema & connector: 4.14.3

### Actual behavior
Failed to invoke the call request

graphClient.communications().calls().post(call);

java.lang.IllegalStateException: Dangling name: applicationInstance
        at com.google.gson.stream.JsonWriter.close(JsonWriter.java:346) ~[gson-2.10.1.jar!/:?]
        at com.google.gson.stream.JsonWriter.endObject(JsonWriter.java:321) ~[gson-2.10.1.jar!/:?]
        at com.microsoft.kiota.serialization.JsonSerializationWriter.writeObjectValue(JsonSerializationWriter.java:316) ~[microsoft-kiota-serialization-json-1.1.7.jar!/:?]
        at com.microsoft.graph.models.ParticipantInfo.serialize(ParticipantInfo.java:138) ~[microsoft-graph-6.7.0.jar!/:?]
        at com.microsoft.kiota.serialization.JsonSerializationWriter.writeObjectValue(JsonSerializationWriter.java:301) ~[microsoft-kiota-serialization-json-1.1.7.jar!/:?]
        at com.microsoft.graph.models.Call.serialize(Call.java:276) ~[microsoft-graph-6.7.0.jar!/:?]
        at com.microsoft.kiota.serialization.JsonSerializationWriter.writeObjectValue(JsonSerializationWriter.java:301) ~[microsoft-kiota-serialization-json-1.1.7.jar!/:?]
        at com.microsoft.kiota.RequestInformation.setContentFromParsable(RequestInformation.java:358) ~[microsoft-kiota-abstractions-1.1.7.jar!/:?]
        at com.microsoft.graph.communications.calls.CallsRequestBuilder.toPostRequestInformation(CallsRequestBuilder.java:159) ~[microsoft-graph-6.7.0.jar!/:?]
        at com.microsoft.graph.communications.calls.CallsRequestBuilder.post(CallsRequestBuilder.java:113) ~[microsoft-graph-6.7.0.jar!/:?]
        at com.microsoft.graph.communications.calls.CallsRequestBuilder.post(CallsRequestBuilder.java:101) ~[microsoft-graph-6.7.0.jar!/:?]

### Steps to reproduce the behavior
Try the sample code as explained in below link

https://learn.microsoft.com/en-us/graph/api/application-post-calls?view=graph-rest-1.0&tabs=java#example-9-create-peer-to-peer-pstn-call-with-service-hosted-media

**Comment by Ndiritu** [comment] 2024-04-29 10:38
@devillaccc thanks for reporting this. Did this work in previous SDK versions?

**Comment by devillaccc** [comment] 2024-04-29 11:23
Yes, its the similar issue with 6.4.0. I followed this forum and its recommended to use latest releases. Hence I used 6.7.0 over 6.4.0

**Comment by baywet** [comment] 2024-04-29 12:48
@Ndiritu could be duplicate of #1930

**Comment by devillaccc** [comment] 2024-04-30 07:23
Hi! Any pointers on this ? Any workaround possible ? Alternate approach ?

**Comment by devillaccc** [comment] 2024-04-30 19:14
What are you suggesting here ?

**Closed** 2024-06-03 11:29 UTC
Labels: type:bug, area:serialization, priority:p1
