### ISSUE TITLE
IllegalArgumentException Unknown pattern character 'X' on version 1.6.

### ISSUE THREAD

**Issue by masahiro-ikemoto** [microsoftgraph/msgraph-sdk-java#286] opened 2019-08-22 02:49 UTC
On version 1.6,

java.lang.IllegalArgumentException: Unknown pattern character 'X'

was thrown from com.microsoft.graph.serializer.CalendarSerializer.deserialize() method on Android 6 or prior devices.

It caused by using SimpleDateFormat pattern charactor 'X' is supported from java 7 but device has java 6 VM.

CalendarSerializer didn't use 'X' pattern before version 1.5.

Would you like to rewrite CalendarSerializer.deserialize() method using no 'X' charactor?

**Comment by bilalgce** [comment] 2019-08-22 07:11
Thanks for reporting this issue. We're looking into this.

**Comment by AlexeyMatrosov** [comment] 2019-11-05 02:10
Hello!
So, is there any progress on this issue. 
I used graph-android and I'm planning to migrate to graph-java (because graph-android apparently no longer supported). 
But I still have this problem at 1.7.1. Because of itI can’t migrate =(

**Comment by rmiragaya** [comment] 2019-11-22 17:36
Hi! 
Im having the same problem when trying to create an UploadSession at 1.7.1 version.

`UploadSession us = this.mClientI
                            .sites().byId(siteIdI)
                            .drives().byId(driveIdI)
                            .items().byId(idCarpeta)
                            .itemWithPath(persona.getScanFileName())
                            .createUploadSession(new DriveItemUploadableProperties())
                            .buildRequest()
                            .post();`

ClientException: Error during http request 
Caused by: IllegalArgumentException: Unknown pattern character 'X'

**Comment by SailReal** [comment] 2020-04-17 19:33
I also run into this issue and had to downgrade to 1.5.0 ...

**Comment by baywet** [comment] 2020-09-14 15:52
Hi everyone,
Thanks for this question and for your patience.
You should be able to get support for this pattern character [through desugaring](https://developer.android.com/studio/write/java8-support#library-desugaring) as it [adds support for patterns](https://developer.android.com/studio/write/java8-support-table#java-time-customizations)

We're looking at bumping the java version to 1.8 with the next major version of this lib so we stay on a supported set of tooling and eco-system. The service replies with offsets in the payload. So we won't be removing this character.
I'll be closing this question as it's old. But feel free to comment on it and I'll re-open it if needs be.

**Closed by baywet** 2020-09-14 15:52 UTC
Labels: question

**Comment by mitoza** [comment] 2020-10-16 10:15
Hi! I want to mention that Graph SDK version 2.3.0 not work properly with Android devices with SDK lower then 6. 
The SimpleDateFormat not work  properly in [CalendarSerializer.java](https://github.com/microsoftgraph/msgraph-sdk-java/blob/dev/src/main/java/com/microsoft/graph/serializer/CalendarSerializer.java) because of 'X' statement because of variable _hasOffset_ put it there. By the way in the original [CalendarSerializer.java](https://github.com/OfficeDev/orc-for-android/blob/master/src/orc-android/src/main/java/com/microsoft/services/orc/serialization/impl/CalendarSerializer.java) there is no variable with name _hasOffset_ .

So my temporary solution was to change Gson object in [DefaultSerializer.java](https://github.com/microsoftgraph/msgraph-sdk-java/blob/dev/src/main/java/com/microsoft/graph/serializer/DefaultSerializer.java) with the Java Reflection.

**Comment by baywet** [comment] 2020-10-16 13:57
@mitoza Thanks for the additional information.
Do you have desugaring enabled for your project?

**Comment by mitoza** [comment] 2020-10-19 10:36
@baywet yes, I'm use for compile/build setups:
Language: Java
defaultConfig {
        minSdkVersion 19
        targetSdkVersion 28
        multiDexEnabled true}

**Comment by baywet** [comment] 2020-10-19 14:39
According to the [documentation](https://developer.android.com/studio/write/java8-support#library-desugaring) yes. Your lib version is a bit behind though.
