### ISSUE TITLE
List sites are not working in v 6.1.0 when working with userName + Password

### ISSUE THREAD

**Issue by ihudedi** [microsoftgraph/msgraph-sdk-java#1800] opened 2024-02-13 08:03 UTC
Hi,
I am trying to perform list sites with username and password and getting empty results.
I have permission to Graph with Site.ReadWrite.All and Files.ReadWrite.All
It's working in ClientSecret but not with userName and Password
Is there any permission that I need to add to enable this?

Thanks,
Itay

**Comment by Ndiritu** [comment] 2024-02-13 14:02
Hi @ihudedi, could you please share a code sample of the enpdoint you're calling.
Depending on the endpoint, delegated access (using a logged in user's credentials) may not be supported:
- https://learn.microsoft.com/en-us/graph/api/site-list?view=graph-rest-1.0&tabs=java
- https://learn.microsoft.com/en-us/graph/api/site-getallsites?view=graph-rest-1.0&tabs=http

**Comment by ihudedi** [comment] 2024-02-13 18:18
Hi @Ndiritu 
See my code below:
        UsernamePasswordCredential usernamePasswordCredential = new UsernamePasswordCredentialBuilder().maxRetry(1).tenantId(tenantId).clientId(clientId).username(userNameAD).password(userPasswordAD).build();

        ClientSecretCredential clientSecretCredential = new ClientSecretCredentialBuilder().clientId(clientId).clientSecret(clientSecret).tenantId(tenantId).build();

 String[] scopes = new String[]{"https://graph.microsoft.com/.default"};


        AzureIdentityAuthenticationProvider authProvider = new AzureIdentityAuthenticationProvider(clientSecretCredential, new String[]{}, scopes);
 GraphServiceClient graphServiceClient = new GraphServiceClient(authProvider);
SiteCollectionResponse siteCollectionResponse = graphServiceClient.sites().get();

When I use clientSecret it fetched the list but with userNamePassword gets empty
Thanks,
Itay

**Comment by ihudedi** [comment] 2024-02-15 09:39
Hi @Ndiritu 
Same issue for version 6.2.0
Thanks,
Itay

**Comment by abhishekmohite** [comment] 2024-03-05 19:47
Similarly, the following code is returning no sites. I am using microsoft-graph 6.4.0 and kiota 1.0.6

```
SiteCollectionResponse allSites = graphClient.sites().get(requestConfiguration -> {
	requestConfiguration.queryParameters.search = "";
});
```

However, the following code works normally. Graph explorer works as well.
```
String sitesURL = "https://graph.microsoft.com/v1.0/sites?search=&$select=id,displayName";

LinkedHashMap<String, String> sitesMap = new LinkedHashMap<String, String>();

URL url = new URL(sitesURL);
HttpURLConnection connection = (HttpURLConnection) url.openConnection();

connection.setDoInput(true);
connection.setDoOutput(true);
connection.setUseCaches(false);
connection.setInstanceFollowRedirects(true);
connection.setRequestMethod("GET");
connection.setRequestProperty("Host", connection.getURL().getHost());
connection.setRequestProperty("Accept", "text/html,application/json,application/xml");
connection.setRequestProperty("Authorization", "Bearer " + accessToken);

connection.setConnectTimeout(5000);
connection.setReadTimeout(5000);

try (InputStream inStream = connection.getInputStream()) {
	JSONObject jsonIn = new JSONObject(new JSONTokener(inStream));

	if (jsonIn.has("value")) {
		// extract content
		JSONArray sitesArray = jsonIn.getJSONArray("value");

		for (int i = 0; i < sitesArray.length(); i++) {

			// store each object in JSONObject  
			JSONObject siteInfo = sitesArray.getJSONObject(i);
			sitesMap.put((String) siteInfo.get("id"), (String) siteInfo.get("displayName"));
		}

	} else {
		// probably bad
		throw new IOException("Unexpected response getting Sites.");
	}
}
```

The old code version with library `5.8.0` worked fine as below.

```
LinkedList<Option> requestOptions = new LinkedList<Option>();
requestOptions.add(new QueryOption("search", "")); // Keep it blank so that it returns all sites

SiteCollectionPage sites = graphClient.sites().buildRequest(requestOptions).get();
```

**Comment by ihudedi** [comment] 2024-03-06 10:54
Hi @abhishekmohite 
In v5.8 they have the query param search.in v6 there is only $search
The new version contains a lot of issues.
Thanks,
Itay

**Comment by baywet** [comment] 2024-03-06 13:25
For everybody's context here:
- [the search endpoint](https://learn.microsoft.com/en-us/graph/api/resources/search-api-overview?view=graph-rest-1.0) is Microsoft Graph's centralized search API and is supported by the SDK today.
- [the $search query parameter](https://learn.microsoft.com/en-us/graph/search-query-parameter?tabs=http) is a normalized way of "narrowing down in a fuzzy way" some collections across Microsoft Graph APIs. This is also supported by the SDK today.
- [the search query parameter](https://devblogs.microsoft.com/microsoft365dev/transition-to-microsoft-graph-search-endpoint-for-onedrive-and-sharepoint/) is a specific query parameter to the sites API, which is not documented in the metadata, thus not present in the SDK. This query parameter is getting deprecated in favour of the global/normalized search capabilities. A challenge the v6 of the SDK is pausing, is the inability to add custom query parameters to the request in a simple way.

Due to the fact this API capability is getting deprecated, we're unlikely to invest time to restore it in the SDK itself, especially since it might conflict with the $seach capability.

If you have feedback about this specific API, please open a support ticket or [reach out on Microsoft Graph Q&A](https://learn.microsoft.com/en-us/answers/tags/161/ms-graph) since the service team is not watching this repository.

I hope this clarifies the situation for everyone.

**Comment by Ndiritu** [comment] 2024-03-07 12:53
> Hi @Ndiritu See my code below: UsernamePasswordCredential usernamePasswordCredential = new UsernamePasswordCredentialBuilder().maxRetry(1).tenantId(tenantId).clientId(clientId).username(userNameAD).password(userPasswordAD).build();
> 
> ```
>     ClientSecretCredential clientSecretCredential = new ClientSecretCredentialBuilder().clientId(clientId).clientSecret(clientSecret).tenantId(tenantId).build();
> ```
> 
> String[] scopes = new String[]{"[https://graph.microsoft.com/.default"}](https://graph.microsoft.com/.default%22%7D);
> 
> ```
>     AzureIdentityAuthenticationProvider authProvider = new AzureIdentityAuthenticationProvider(clientSecretCredential, new String[]{}, scopes);
> ```
> 
> GraphServiceClient graphServiceClient = new GraphServiceClient(authProvider); SiteCollectionResponse siteCollectionResponse = graphServiceClient.sites().get();
> 
> When I use clientSecret it fetched the list but with userNamePassword gets empty Thanks, Itay

Was able to reproduce this. From the [docs](https://learn.microsoft.com/en-us/graph/api/site-list?view=graph-rest-1.0&tabs=http#list-all-site-collections), only application permissions are supported. Using a delegated authentication like username-password/authorization code returns an empty list.

**Comment by ihudedi** [comment] 2024-03-07 13:02
Hi @Ndiritu 
So how can I get site list using username and password?
Thanks,
Itay

**Comment by baywet** [comment] 2024-03-08 01:07
Please refer to my previous answer about service related questions. Closing this one since we clearly identified it's not related to the SDK but it's rather a service behaviour question.

**Closed by baywet** 2024-03-08 01:07 UTC
Labels: question, Needs: Attention :wave:
