### ISSUE TITLE
CustomRequest has to be <T1, T2> extends BaseRequest 

### ISSUE THREAD

**Issue by glani** [microsoftgraph/msgraph-sdk-java#267] opened 2019-07-03 22:28 UTC
### Expected behavior
CustomRequest<T1, T2> extends BaseRequest
### Actual behavior
CustomRequest<T> extends BaseRequest

### Steps to reproduce the behavior
core of SDK

It does not make sense to have such custom request with the same input and output data.

I want to use it to get a new token from "refresh_token" using custom http request. However it is impossible to perform only one workaround to implement own request such as:
public class OneDriveCustomRequest<T1, T2> extends BaseRequest {

    private OneDriveCustomRequest(final String requestUrl,
                                  final IBaseClient client,
                                  final java.util.List<? extends Option> requestOptions,
                                  final Class<T2> responseClass) {
        super(requestUrl, client, requestOptions, responseClass);
    }

It has remained unclear the purpose of original CustomRequest.

Could you please explain ?

**Comment by baywet** [comment] 2020-09-22 14:12
closing as duplicate of #25

**Closed by baywet** 2020-09-22 14:12 UTC
Labels: enhancement
