### ISSUE TITLE
How to fetch the active cell address

### ISSUE THREAD

**Issue by ashish777gupta** [microsoftgraph/msgraph-sdk-java#2002] opened 2024-05-17 06:08 UTC
I want to retrieve the address of the **active cell** in the worksheet. The active cell address is the last modified cell in the sheet where the cell cursor is currently located. 
For example, in the below sheet the active cell address is : C2
![image](https://github.com/microsoftgraph/msgraph-sdk-java/assets/81915943/5c2bfecb-dbd3-4506-bc59-04ef905f99fe)

Please tell me what the API is for retrieving the active cell in java sdk.

**Comment by petrhollayms** [comment] 2024-05-29 14:03
Hi @ashish777gupta ,

The REST API documentation is here: https://learn.microsoft.com/en-us/graph/api/resources/excel?view=graph-rest-1.0
I am not sure the Excel API in Graph does support the operation you are looking for.

his appears to be an issue or limitation with the service APIs. Unfortunately, as the Microsoft Graph SDK team, we do not have ownership of the APIs that are causing you issues. We invite you to create a question about the service API to Microsoft Q&A and tagged with one of the [microsoft-graph-*] tags, that way it will get routed to the appropriate team for them to triage:  
 
https://aka.ms/msgraphsupport or directly https://aka.ms/askgraph 

For now, we will close the issue on our side but feel free to open it in the relevant repository if you think the issue is specific to SDK.

**Closed by petrhollayms** 2024-05-29 14:03 UTC
