### ISSUE TITLE
Android Release OneDrive API not working

### ISSUE THREAD

**Issue by lebedevsd1** [microsoftgraph/msgraph-sdk-java#213] opened 2019-01-18 16:20 UTC
Hey guys,

I am using this library for android, and there are no problems with Debug version, but I am receiving errors for release version with enabled minification and proguard

### Expected behavior

I should be able to load folders of user that are presented in oneDrive
```
graphClient.drive().root().children().buildRequest().get(new ICallback<IDriveItemCollectionPage>() {
                    @Override
                    public void success(IDriveItemCollectionPage iDriveItemCollectionPage) {
                        for (DriveItem driveItem : iDriveItemCollectionPage.getCurrentPage()) {
                        }
                    }
                    @Override
                    public void failure(ClientException ex) {
                        logException(ex.getCause());
                    }
};
```

### Actual behavior

I receive 
```
2019-01-18 17:03:02.929 18445-19364/? E/global: DefaultHttpProvider[sendRequestInternal] - 358Error during http request
2019-01-18 17:03:02.929 18445-19364/? E/global: Throwable detail: com.microsoft.graph.core.ClientException: Error during http request
```

### Steps to reproduce the behavior

Build an android app with enabled minification and proguard.
```
-keepclasseswithmembernames class com.microsoft.** { *; }
```

**Comment by deepak2016** [comment] 2019-01-22 06:04
Thanks for reporting the issue. We are looking into it.

**Comment by dknchris** [comment] 2019-05-03 12:26
`E/global: DefaultHttpProvider[sendRequestInternal] - 370Error during http request`
`E/global: Throwable detail: com.microsoft.graph.core.ClientException: Error during http request`

Can confirm the exact issue...The lines outputted too are pretty generic. Please expedite this issue as currently there doesn't seem like anyway to use this in production apps with Proguard/R8 enabled. If someone has any workarounds, kindly drop a comment here.

**Comment by fiasko131** [comment] 2019-06-02 23:00
The same issue here. Can not compile with proguard in release.
I have tried a lot of things for three days.

````java
activity.mGraphClient.me().drive().buildRequest().get(callback )
````

> DefaultHttpProvider[sendRequestInternal] - 370Error during http request
Throwable detail: com.microsoft.graph.core.ClientException: Error during http reque

and 

> com.microsoft.graph.core.ClientException: Error during http requ
at com.microsoft.graph.http.DefaultHttpProvider.sendRequestInternal(:368)
at com.microsoft.graph.http.DefaultHttpProvider.access$000(:53)
at com.microsoft.graph.http.DefaultHttpProvider$1.run(:155)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
at java.lang.Thread.run(Thread.java:764)
Caused by: java.lang.RuntimeException: java.lang.ClassNotFoundException: com.sun.ws.rs.ext.RuntimeDelegateImpl
at javax.ws.rs.ext.RuntimeDelegate.findDelegate(:122)
at javax.ws.rs.ext.RuntimeDelegate.getInstance(:91)
at javax.ws.rs.core.UriBuilder.newInstance(:69)
at javax.ws.rs.core.UriBuilder.fromUri(:80)
at com.microsoft.graph.http.BaseRequest.getRequestUrl(:147)
at com.microsoft.graph.http.DefaultHttpProvider.sendRequestInternal(:239)
com.techniwork.fastsharing W/System.err

Proguard file :

> -keep class com.microsoft.** { *; }
-keep class com.microsoft.**
-keep interface com.microsoft.** { *; }
-keepclasseswithmembernames class com.microsoft.** { *; }

>-keep class com.sun.ws.** { *; }
-keep class com.sun.ws.**
-keep interface com.sun.ws.** { *; }

>-keep class com.sun.jersey.** { *; }

-keep class com.sun.jersey.**
-keep interface com.sun.jersey.** { *; }

> +--- com.microsoft.graph:microsoft-graph:1.4.+ -> 1.4.0
|    +--- org.apache.commons:commons-math3:3.6.1
|    +--- com.google.code.gson:gson:2.8.2
|    +--- com.sun.jersey:jersey-server:1.19.4
|    |    \--- com.sun.jersey:jersey-core:1.19.4
|    |         \--- javax.ws.rs:jsr311-api:1.1.1
|    \--- com.google.guava:guava:20.0 -> 25.1-android
|         +--- com.google.code.findbugs:jsr305:3.0.2
|         +--- org.checkerframework:checker-compat-qual:2.0.0
|         +--- com.google.errorprone:error_prone_annotations:2.1.3
|         +--- com.google.j2objc:j2objc-annotations:1.1
|         \--- org.codehaus.mojo:animal-sniffer-annotations:1.14

Thank you for taking this into account and help me find a solution ... I am desperate ..

**Comment by Samhithgb** [comment] 2019-10-16 13:23
Were you able to resolve this? Any pointers will be appreciated.

**Comment by andj207** [comment] 2020-03-09 13:29
The same issue when enable proguard in release build

proguard rules:

    # Microsoft Graph API
    -keepnames class com.microsoft.** implements java.io.Serializable
    -keepnames class com.microsoft.graph.models.** { *; }
    -keepnames class com.microsoft.identity.** { *; }

    -keep class com.microsoft.** implements java.io.Serializable {
        !private <init>();
    }

    -keep class com.microsoft.graph.models.** {
        !private <init>();
    }

    -keep class com.microsoft.identity.** {
        !private <init>();
    }

Crash:

    com.microsoft.graph.core.ClientException: Error during http request
        at f.z.b.d.h.a(CoreHttpProvider.java:421)
        at f.z.b.d.h.a(CoreHttpProvider.java:204)
        at f.z.b.d.h.a(CoreHttpProvider.java:184)
        at f.z.b.d.c.i(BaseCollectionRequest.java:89)
        at f.z.b.h.a.j2.j(DriveItemCollectionRequest.java:52)
        at f.z.b.h.a.i2.run(DriveItemCollectionRequest.java:43)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.lang.RuntimeException: java.lang.ClassNotFoundException: com.sun.ws.rs.ext.RuntimeDelegateImpl
        at l.b.a.b.c.a(RuntimeDelegate.java:122)
        at l.b.a.b.c.b(RuntimeDelegate.java:91)
        at l.b.a.a.a.a(UriBuilder.java:69)
        at l.b.a.a.a.a(UriBuilder.java:80)
        at f.z.b.d.d.b(BaseRequest.java:176)
        at f.z.b.d.c.b(BaseCollectionRequest.java:112)
        at f.z.b.d.h.a(CoreHttpProvider.java:237)
        at f.z.b.d.h.a(CoreHttpProvider.java:204) 
        at f.z.b.d.h.a(CoreHttpProvider.java:184) 
        at f.z.b.d.c.i(BaseCollectionRequest.java:89) 
        at f.z.b.h.a.j2.j(DriveItemCollectionRequest.java:52) 
        at f.z.b.h.a.i2.run(DriveItemCollectionRequest.java:43) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636) 
        at java.lang.Thread.run(Thread.java:764) 
     Caused by: java.lang.ClassNotFoundException: com.sun.ws.rs.ext.RuntimeDelegateImpl
        at java.lang.Class.classForName(Native Method)
        at java.lang.Class.forName(Class.java:453)
        at java.lang.Class.forName(Class.java:378)
        at l.b.a.b.b.a(FactoryFinder.java:62)
        at l.b.a.b.b.a(FactoryFinder.java:155)
        at l.b.a.b.c.a(RuntimeDelegate.java:105)
        at l.b.a.b.c.b(RuntimeDelegate.java:91) 
        at l.b.a.a.a.a(UriBuilder.java:69) 
        at l.b.a.a.a.a(UriBuilder.java:80) 
        at f.z.b.d.d.b(BaseRequest.java:176) 
        at f.z.b.d.c.b(BaseCollectionRequest.java:112) 
        at f.z.b.d.h.a(CoreHttpProvider.java:237) 
        at f.z.b.d.h.a(CoreHttpProvider.java:204) 
        at f.z.b.d.h.a(CoreHttpProvider.java:184) 
        at f.z.b.d.c.i(BaseCollectionRequest.java:89) 
        at f.z.b.h.a.j2.j(DriveItemCollectionRequest.java:52) 
        at f.z.b.h.a.i2.run(DriveItemCollectionRequest.java:43) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636) 
        at java.lang.Thread.run(Thread.java:764) 
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.sun.ws.rs.ext.RuntimeDelegateImpl" on path: DexPathList[[zip file "/data/app/com.flowiemusic.tiles.mp3.player.magictiles-5vKwBPcf-f3yF414EgNZqw==/base.apk"],nativeLibraryDirectories=[/data/app/com.flowiemusic.tiles.mp3.player.magictiles-5vKwBPcf-f3yF414EgNZqw==/lib/x86, /data/app/com.flowiemusic.tiles.mp3.player.magictiles-5vKwBPcf-f3yF414EgNZqw==/base.apk!/lib/x86, /system/lib, /vendor/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:125)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at java.lang.Class.classForName(Native Method) 
        at java.lang.Class.forName(Class.java:453) 
        at java.lang.Class.forName(Class.java:378) 
        at l.b.a.b.b.a(FactoryFinder.java:62) 
        at l.b.a.b.b.a(FactoryFinder.java:155) 
        at l.b.a.b.c.a(RuntimeDelegate.java:105) 
        at l.b.a.b.c.b(RuntimeDelegate.java:91) 
        at l.b.a.a.a.a(UriBuilder.java:69) 
        at l.b.a.a.a.a(UriBuilder.java:80) 
        at f.z.b.d.d.b(BaseRequest.java:176) 
        at f.z.b.d.c.b(BaseCollectionRequest.java:112) 
        at f.z.b.d.h.a(CoreHttpProvider.java:237) 
        at f.z.b.d.h.a(CoreHttpProvider.java:204) 
        at f.z.b.d.h.a(CoreHttpProvider.java:184) 
        at f.z.b.d.c.i(BaseCollectionRequest.java:89) 
        at f.z.b.h.a.j2.j(DriveItemCollectionRequest.java:52) 
        at f.z.b.h.a.i2.run(DriveItemCollectionRequest.java:43) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636) 
        at java.lang.Thread.run(Thread.java:764)

**Comment by atulgpt** [comment] 2020-08-26 15:02
@deepak2016 It's been more than 1.5 years, is this issue got resolved?

**Comment by baywet** [comment] 2020-09-04 13:01
Hey everyone.
Thanks for your feedback and for your patience on the matter.
I've authored #449 which removes the dependency all together (to replace it by okhttp which the core lib already depends on).
This PR will fix this issue (and close it when it gets merged).

**Closed** 2020-09-09 15:57 UTC
Labels: bug, fixed
