### ISSUE TITLE
 com.google.gson.stream.MalformedJsonException: Unterminated array at line 1 column 6143 path $.value[5]

### ISSUE THREAD

**Issue by davidkarlsen** [microsoftgraph/msgraph-sdk-java#694] opened 2021-03-12 23:33 UTC
### Expected behavior

Should list groups fine

### Actual behavior
exception:

```
com.microsoft.graph.core.ClientException: Error during http request
	at com.microsoft.graph.http.CoreHttpProvider.sendRequestInternal(CoreHttpProvider.java:471)
	at com.microsoft.graph.http.CoreHttpProvider.send(CoreHttpProvider.java:220)
	at com.microsoft.graph.http.CoreHttpProvider.send(CoreHttpProvider.java:200)
	at com.microsoft.graph.http.BaseCollectionRequest.send(BaseCollectionRequest.java:92)
	at com.microsoft.graph.requests.extensions.GroupCollectionWithReferencesRequest.get(GroupCollectionWithReferencesRequest.java:56)
	at com.evry.fs.devtools.ad.AzureAdUserServiceImpl.findByEmail(AzureAdUserServiceImpl.java:153)
	at com.evry.fs.devtools.ad.AzureAdUserServiceImpl$$FastClassBySpringCGLIB$$8c469a13.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:779)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750)
	at org.springframework.validation.beanvalidation.MethodValidationInterceptor.invoke(MethodValidationInterceptor.java:123)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:692)
	at com.evry.fs.devtools.ad.AzureAdUserServiceImpl$$EnhancerBySpringCGLIB$$38a2b72c.findByEmail(<generated>)
	at com.evry.fs.devtools.employee.CompositeUserService.findByEmail(CompositeUserService.java:32)
	at com.evry.fs.devtools.employee.CompositeUserService$$FastClassBySpringCGLIB$$65728e53.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:779)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750)
	at org.springframework.cache.interceptor.CacheInterceptor.lambda$invoke$0(CacheInterceptor.java:54)
	at org.springframework.cache.interceptor.CacheAspectSupport.invokeOperation(CacheAspectSupport.java:366)
	at org.springframework.cache.interceptor.CacheAspectSupport.execute(CacheAspectSupport.java:421)
	at org.springframework.cache.interceptor.CacheAspectSupport.execute(CacheAspectSupport.java:345)
	at org.springframework.cache.interceptor.CacheInterceptor.invoke(CacheInterceptor.java:64)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:692)
	at com.evry.fs.devtools.employee.CompositeUserService$$EnhancerBySpringCGLIB$$44df53f.findByEmail(<generated>)
	at com.evry.fs.devtools.ghe.GheService.checkValid(GheService.java:88)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceTask.doLeaf(ReduceOps.java:952)
	at java.base/java.util.stream.ReduceOps$ReduceTask.doLeaf(ReduceOps.java:926)
	at java.base/java.util.stream.AbstractTask.compute(AbstractTask.java:327)
	at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:746)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Unterminated array at line 1 column 6143 path $.value[5]
	at com.google.gson.Gson.fromJson(Gson.java:947)
	at com.google.gson.Gson.fromJson(Gson.java:897)
	at com.google.gson.Gson.fromJson(Gson.java:846)
	at com.google.gson.Gson.fromJson(Gson.java:817)
	at com.microsoft.graph.serializer.DefaultSerializer.deserializeObject(DefaultSerializer.java:82)
	at com.microsoft.graph.http.CoreHttpProvider.handleJsonResponse(CoreHttpProvider.java:532)
	at com.microsoft.graph.http.CoreHttpProvider.sendRequestInternal(CoreHttpProvider.java:448)
	... 48 common frames omitted
Caused by: com.google.gson.stream.MalformedJsonException: Unterminated array at line 1 column 6143 path $.value[5]
	at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1564)
	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:477)
	at com.google.gson.stream.JsonReader.hasNext(JsonReader.java:415)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:81)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:61)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
	at com.google.gson.Gson.fromJson(Gson.java:932)
	... 54 common frames omitted
```

### Steps to reproduce the behavior

happens randomly

 
[AB#8585](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/8585)

**Comment by baywet** [comment] 2021-03-15 12:20
Hey @davidkarlsen 
Thanks for reaching out. Can you provide the following:
- SDK version in use
- core version in use
- a snippet of the code that reproduces the issue

If you're not on sdk 2.10.0 and core 1.0.9, can you please upgrade and see if you're running into the same issue?
Thanks!

**Comment by davidkarlsen** [comment] 2021-03-15 14:34
core: 1.0.9
sdk: 2.10.0

code:
```
public Optional<AdUser> findByEmail(@NotEmpty @Email String email) {
    var iUserCollectionPage =
        graphServiceClient
            .users()
            .buildRequest()
            .filter(
                String.format(
                    "startsWith(mail,'%s') OR startsWith(userPrincipalName, '%s') OR proxyAddresses/any(x:startsWith(x, 'smtp:%s')) OR otherMails/any(x:startsWith(x, '%s'))",
                    email, email, email, email))
            // userType,preferredName
            .select(
                "otherMails,accountEnabled,employeeId,displayName,givenName,mail,mailNickname,mobilePhone,otherMails,proxyAddresses,surname,userPrincipalName,id")
            .get();
    logger.trace("{}", iUserCollectionPage);
    var optionalUser = iUserCollectionPage.getCurrentPage().stream().findAny();

    if (optionalUser.isEmpty()) {
      return Optional.empty();
    } else {
      Collection<Group> groups;
      try {
// this is the problematic call:
        groups =
            graphServiceClient
                .users(optionalUser.get().id)
                .transitiveMemberOfAsGroup()
                .buildRequest(Arrays.asList(new HeaderOption("ConsistencyLevel", "eventual")))
                .get()
                .getCurrentPage();
      } catch (Exception e) {
        logger.error("Error fetcing groups for [{}] - returning empty set", email, e);
        groups = Collections.emptySet();
      }
      return Optional.of(new AdUser(optionalUser.get(), groups));
    }
  }
```

**Comment by baywet** [comment] 2021-03-16 14:51
thanks for the additional information. Looking at the responses I'm getting trying to reproduce the issue, it looks like the service is interrupting the array response with the odata error in some cases. This leads to something that's impossible to parse on the client side. As we already have a service issue logged, I'm going to close this issue as a duplicate. https://github.com/microsoftgraph/msgraph-sdk-serviceissues/issues/37

**Closed by baywet** 2021-03-16 14:51 UTC
Labels: Needs: Attention :wave:, question
