### ISSUE TITLE
Jar file of graph api version 6.7 increased in 40MB than version 5.8

### ISSUE THREAD

**Issue by ihudedi** [microsoftgraph/msgraph-sdk-java#1974] opened 2024-04-30 11:08 UTC
Hi,
The jar file for microsoft-graph-5.80.0.jar was 11599291 (11.1 MB)
The jar file for microsoft-graph-6.7.0.jar is       50705345       (48.4 MB)
Seems like a big difference.
Can I remove redundant packages If I am using only connectivity to SharePoint
Thanks,
Itay

**Comment by baywet** [comment] 2024-04-30 11:46
closing as duplicate of #1857

**Closed by baywet** 2024-04-30 11:46 UTC
