### ISSUE TITLE
Packetloss and VideoFrameRate not reported as NULL

### ISSUE THREAD

**Issue by ponrajit** [microsoftgraph/msgraph-sdk-java#567] opened 2020-11-24 12:37 UTC
### Expected behavior

The PacketLoss and VideoFrameRate under "Streams" in the Call Record should be reported as NULL like other metrics when they are not available.

### Actual behavior
PacketLoss and VideoFrameRate are reported as float and set to 0.0.

**Comment by baywet** [comment] 2020-11-24 12:53
Hi @ponrajit 
Thanks for reaching out.
Can you please share a code sample to reproduce the issue? as well as the JSON payload you're receiving from the service.
Thanks!

**Comment by ponrajit** [comment] 2020-11-24 13:05
Hi @baywet 

The "streams" JSON data containing packetloss and videoframerate
"streams": [
                                {
                                    "streamId": "12976",
                                    "startDateTime": null,
                                    "endDateTime": null,
                                    "streamDirection": "callerToCallee",
                                    "averageAudioDegradation": null,
                                    "averageJitter": null,
                                    "maxJitter": null,
                                    **"averagePacketLossRate": null,**
                                    "maxPacketLossRate": null,
                                    "averageRatioOfConcealedSamples": null,
                                    "maxRatioOfConcealedSamples": null,
                                    "averageRoundTripTime": null,
                                    "maxRoundTripTime": null,
                                    "packetUtilization": 0,
                                    "averageBandwidthEstimate": null,
                                    "wasMediaBypassed": null,
                                    "postForwardErrorCorrectionPacketLossRate": null,
                                    "averageVideoFrameLossPercentage": null,
                                    "averageReceivedFrameRate": null,
                                    "lowFrameRateRatio": null,
                                    "averageVideoPacketLossRate": null,
                                    **"averageVideoFrameRate": null,**
                                    "lowVideoProcessingCapabilityRatio": null,
                                    "averageAudioNetworkJitter": null,
                                    "maxAudioNetworkJitter": null
                                },
                                {
                                    "streamId": "3303",
                                    "startDateTime": null,
                                    "endDateTime": null,
                                    "streamDirection": "calleeToCaller",
                                    "averageAudioDegradation": null,
                                    "averageJitter": "PT0S",
                                    "maxJitter": "PT0S",
                                    **"averagePacketLossRate": 0,**
                                    "maxPacketLossRate": 0,
                                    "averageRatioOfConcealedSamples": null,
                                    "maxRatioOfConcealedSamples": null,
                                    "averageRoundTripTime": "PT0.02S",
                                    "maxRoundTripTime": "PT0.02S",
                                    "packetUtilization": 1184,
                                    "averageBandwidthEstimate": null,
                                    "wasMediaBypassed": null,
                                    "postForwardErrorCorrectionPacketLossRate": 0,
                                    "averageVideoFrameLossPercentage": 0,
                                    "averageReceivedFrameRate": null,
                                    "lowFrameRateRatio": 0,
                                    "averageVideoPacketLossRate": null,
                                    **"averageVideoFrameRate": 25.6,**
                                    "lowVideoProcessingCapabilityRatio": null,
                                    "averageAudioNetworkJitter": null,
                                    "maxAudioNetworkJitter": null
                                }
                            ]

Code to get the packetloss and videoframerate
float packetLossRate = stream.averagePacketLossRate;
float videoFrameRate = stream.averageVideoFrameRate;

Thanks

**Comment by baywet** [comment] 2020-11-25 18:24
Thank you for the additional information. This bug is caused by the fact our code generation process is mapping Edm.Single to float and not Float (Nullable). Even though the impact is limited, this would introduce a breaking change and the fix needs to wait for the next major release.
I authored #570 which addresses the issue and will clause it whenever it gets merged.

**Closed** 2020-11-26 17:27 UTC
Labels: bug, fixed
