### ISSUE TITLE
Error on subsciption get/patch/delete, [Status Code: Unauthorized; Reason: p#S256 doesn't match

### ISSUE THREAD

**Issue by nikhil452** [microsoftgraph/msgraph-sdk-java#1711] opened 2023-12-15 05:34 UTC
We are facing the below problem when executing get/patch/delete operations on the ["https://graph.microsoft.com/v1.0/subscriptions"](https://graph.microsoft.com/v1.0/subscriptions,) endpoint. Although I can successfully create a subscription, I encounter the following error when attempting delete/get/patch operations.

Response :
{
"error": {
"code": "ExtensionError",
"message": "Operation: Update; Exception: [Status Code: Unauthorized; Reason: p#S256 doesn't match.]",
"innerError": {
"date": "2023-12-14T11:05:30",
"request-id": "0d73eea2-5671-4c2c-b9db-8dd0220c26aa",
"client-request-id": "0d73eea2-5671-4c2c-b9db-8dd0220c26aa"
}
}
}

**Comment by Vadi** [comment] 2023-12-15 13:43
We're running into same error. This requires immediate attention

**Comment by gilb77** [comment] 2023-12-15 14:03
We get the same response error, this subscription operations works for us until yesterday.

Any update @ramsessanchez?

**Comment by chughpiyush** [comment] 2023-12-15 14:04
We are also facing the same issue. @ramsessanchez Please look into this as it is affecting our work.

**Comment by baywet** [comment] 2023-12-15 14:11
Hi everyone,
Thanks for reaching out.
Could you let us know whether this is an issue you're facing after code changes/on new applications, or whether applications already in production without recent code changes started failing?

**Comment by baywet** [comment] 2023-12-15 14:15
Also please share additional client-request-id and UTC dates like @nikhil452 did in the initial message

**Comment by chughpiyush** [comment] 2023-12-15 14:19
@baywet For us, it started occurring on the existing production app (without any recent code changes). The error was logged in our service on `2023-12-12T04:30:03.412Z` for the first time.

```json
{
    "error": {
        "code": "ExtensionError",
        "message": "Operation: Update; Exception: [Status Code: Unauthorized; Reason: p#S256 doesn't match.]",
        "innerError": {
            "date": "2023-12-15T13:43:40",
            "request-id": "0f2dc996-ab65-4ed6-8efd-84ba76cddf87",
            "client-request-id": "0f2dc996-ab65-4ed6-8efd-84ba76cddf87"
        }
    }
}
```

**Comment by baywet** [comment] 2023-12-15 14:46
Thanks for confirming. This repository is dedicated to the SDK itself, and doesn't get attention from the service team.
I however create a high priority incident on the concerned service team https://portal.microsofticm.com/imp/v3/incidents/incident/450997357

Please open [support tickets](https://developer.microsoft.com/en-us/graph/support) mentioning this incident, the more tenants impacts, the higher priority this issue will get.

**Comment by gitomjk** [comment] 2023-12-15 22:02
@baywet could you, please, add this thread to the incident? The issue might not be related to the SDK:
https://techcommunity.microsoft.com/t5/microsoft-graph/error-on-subsciption-get-post-patch-delete-status-code/m-p/4008534

**Comment by baywet** [comment] 2023-12-15 22:10
Added to the incident.
Between the backend logs, and the fact the issue can be reproduced in postman, dotnet and java most likely means the root cause is not in the SDK.
At this time the Microsoft Graph and SharePoint service teams are still investigating the issue.

**Comment by baywet** [comment] 2023-12-16 14:47
Hey everyone,
Quick update to let you know the service team had mitigated the issue and the service should behave normally.
Key us know if you need anything else.
Closing.

**Closed by baywet** 2023-12-16 14:47 UTC
Labels: question, Needs: Attention :wave:
