### ISSUE TITLE
APK for UI Automation is not generating while using the lib

### ISSUE THREAD

**Issue by atulgpt** [microsoftgraph/msgraph-sdk-java#450] opened 2020-09-03 20:59 UTC
Hi I am using the library and it is compiling and creating an APK in debug as well as release variant(with R8 on). But issue comes when we do automation testing(when androidTest is run) on the application as the generation of the test APK gets failed when this library is used. When I comment out the Gradle dependency of the library issue gets resolved. 
I am also attaching the sample Android project where this issue is reproducing in this [share link](https://drive.google.com/file/d/1eP9caGeHsc4oGJraB5qY9k745TgThFvm/view?usp=sharing).

Gradle logs where androidTest fails:
Task :app:minifyDebugAndroidTestWithR8 FAILED

FAILURE: Build failed with an exception.

 \* What went wrong:
Execution failed for task ':app:minifyDebugAndroidTestWithR8'.
GC overhead limit exceeded

Gradle logs with --stacktrace
\* What went wrong:
Execution failed for task ':app:minifyDebugAndroidTestWithR8'.
\> GC overhead limit exceeded

\* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.

\* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app:minifyDebugAndroidTestWithR8'.
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.lambda$executeIfValid$1(ExecuteActionsTaskExecuter.java:205)
	at org.gradle.internal.Try$Failure.ifSuccessfulOrElse(Try.java:263)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:203)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:184)
	at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:109)
	at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:46)
	at org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter.execute(ResolveTaskExecutionModeExecuter.java:62)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:57)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:56)
	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:36)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:77)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:55)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:52)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:416)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:406)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:102)
	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.call(DelegatingBuildOperationExecutor.java:36)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:52)
	at org.gradle.execution.plan.LocalTaskNodeExecutor.execute(LocalTaskNodeExecutor.java:41)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:372)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:359)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:352)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:338)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.lambda$run$0(DefaultPlanExecutor.java:127)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:191)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.executeNextNode(DefaultPlanExecutor.java:182)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:124)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
Caused by: java.lang.OutOfMemoryError: GC overhead limit exceeded
	at com.android.tools.r8.naming.D.a(:12)
	at com.android.tools.r8.naming.E.b(:1)
	at com.android.tools.r8.naming.r.b(:3)
	at com.android.tools.r8.naming.r$$Lambda$1699/2116448445.accept(Unknown Source)
	at com.android.tools.r8.naming.r.c(:2)
	at com.android.tools.r8.naming.r$$Lambda$1697/1967472121.accept(Unknown Source)
	at com.android.tools.r8.naming.r.a(:37)
	at com.android.tools.r8.naming.r$$Lambda$1698/1055070058.apply(Unknown Source)
	at com.android.tools.r8.naming.r.c(:6)
	at com.android.tools.r8.naming.r.a(:46)
	at com.android.tools.r8.naming.r.a(:36)
	at com.android.tools.r8.naming.r.c(:1)
	at com.android.tools.r8.naming.q.b(:6)
	at com.android.tools.r8.naming.q$$Lambda$1695/338335214.accept(Unknown Source)
	at com.android.tools.r8.naming.q.a(:33)
	at com.android.tools.r8.naming.q$$Lambda$1696/1332014033.apply(Unknown Source)
	at com.android.tools.r8.naming.q.a(:36)
	at com.android.tools.r8.naming.q.a(:32)
	at com.android.tools.r8.naming.q.b(:3)
	at com.android.tools.r8.naming.s.a(:205)
	at com.android.tools.r8.naming.x.a(:22)
	at com.android.tools.r8.naming.P.a(:97)
	at com.android.tools.r8.R8.a(:586)
	at com.android.tools.r8.R8.c(:1)
	at com.android.tools.r8.R8.b(:1)
	at com.android.tools.r8.R8$$Lambda$1009/596686148.run(Unknown Source)
	at com.android.tools.r8.utils.W.a(:30)

Also my **Android Studio configurations** are as follow:
**Android Studio 4.0.1**
Build #AI-193.6911.18.40.6626763, built on June 25, 2020
Runtime version: 1.8.0_242-release-1644-b3-6222593 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.6
GC: ParNew, ConcurrentMarkSweep
Memory: 2988M
Cores: 12
Registry: ide.new.welcome.screen.force=true, ide.balloon.shadow.size=0
Non-Bundled Plugins: com.android.aas, com.android.tool.sizereduction.plugin, com.developerphil.adbidea, com.google.services.firebase, de.netnexus.camelcaseplugin, izhangzhihao.rainbow.brackets, org.sonarlint.idea, wu.seal.tool.jsontokotlin

My machine configuration are as follow: MacBook Pro (15-inch, 2018)

### Expected behavior
Test APK should be generated as usual

### Actual behavior
Test APK is not getting generated

### Steps to reproduce the behavior
Run the **TestTestApkFailing** androidTest in the sample app

**Comment by baywet** [comment] 2020-09-03 21:04
What version of the library are you using?

**Comment by atulgpt** [comment] 2020-09-04 11:38
Hi @baywet right now I am using com.microsoft.graph:microsoft-graph:2.0.+ 
In the sample app as well you will find the library version in app level build.gradle

I am also pasting the build.gradle of the sample app:
apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply plugin: 'kotlin-android-extensions'

android {
    compileSdkVersion 28

    defaultConfig {
        applicationId "com.app.testapkfailing"
        minSdkVersion 21
        targetSdkVersion 28
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
        debug {
            crunchPngs true
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
//            testProguardFiles 'src/test/proguard-project.txt'
            shrinkResources false
            testCoverageEnabled true
        }
    }

    packagingOptions {
        pickFirst 'META-INF/jersey-module-version'
    }

//    dexOptions {
//        incremental false
//        javaMaxHeapSize "2048M"
//        preDexLibraries = false
//    }
}

dependencies {
    implementation fileTree(dir: "libs", include: ["*.jar"])
    implementation "org.jetbrains.kotlin:kotlin-stdlib:$kotlin_version"
    implementation 'androidx.core:core-ktx:1.3.1'
    implementation 'androidx.appcompat:appcompat:1.2.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.0.1'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'androidx.test.ext:junit:1.1.1'

    // Unit Test and Instrumented Test
    androidTestImplementation('androidx.test.espresso:espresso-core:3.1.0')
    androidTestImplementation('androidx.test.espresso:espresso-web:3.1.0')

    // Core library
    androidTestImplementation 'androidx.test:core:1.2.0'

    // AndroidJUnitRunner and JUnit Rules
    androidTestImplementation 'androidx.test:runner:1.2.0'
    androidTestImplementation 'androidx.test:rules:1.2.0'
    androidTestImplementation 'androidx.test.uiautomator:uiautomator:2.2.0'

    implementation 'com.microsoft.graph:microsoft-graph:2.0.+'

    // This library controls how users sign-in and access services.
    // We recommend you always take the latest version of our library in your app when you can.
    // We use semantic versioning so you can control the risk of updating your app.
    // For example, always downloading the latest minor version number (e.g. x.y.x) ensures you get the latest security
    // and feature enhancements with the assurance that our API surface area has not changed.
    // @see https://github.com/AzureAD/microsoft-authentication-library-for-android#security-library
    // noinspection GradleDynamicVersion
    implementation('com.microsoft.identity.client:msal:1.+')
}

**Comment by baywet** [comment] 2020-09-04 21:24
This might already be fixed by #449 which should go out with version 2.1.0.
2.1.0 should go out sometime next week. I suggest we wait until then so you can try with that version.

**Comment by atulgpt** [comment] 2020-09-05 12:11
@baywet Thanks for the update. Just want to confirm that did the issue get reproduced with the sample project and it got fixed with the #449 PR?

**Comment by baywet** [comment] 2020-09-05 13:37
No, I haven't had time to try it out yet unfortunately.

**Comment by atulgpt** [comment] 2020-09-05 13:59
@baywet Okay then I will update you after trying the 2.1.0 version. I have seen the changes it doesn't seem to be related to this issue. Let's hope for the best anyway..:)

**Comment by baywet** [comment] 2020-09-09 16:54
FYI 2.1.0 is out

**Comment by atulgpt** [comment] 2020-09-15 19:34
Thanks @baywet for the update. I am trying the build. Will let you know if this works or not.

**Comment by atulgpt** [comment] 2020-09-15 21:07
Hi @baywet I have tried to run the sample app with latest dependency but still it gave the same error.
Dependency that I have added is as follow:
implementation('com.microsoft.graph:microsoft-graph:2.1.0'){
        exclude group: 'org.hamcrest'
 }
I have to exclude the org.hamcrest as that was giving the duplicate class error

**Comment by baywet** [comment] 2020-09-16 11:40
ok thanks for letting me know. I'll have to investigate this one further.
FYI, if you upgrade core to 1.0.3 and remove the exclusion, you should not get the duplication anymore.

**Comment by baywet** [comment] 2020-09-16 12:41
actually, can you have a lot at this answer and check whether you're missing any of the rules here?
https://github.com/microsoftgraph/msgraph-sdk-java/issues/462#issuecomment-693378029

**Comment by atulgpt** [comment] 2020-09-16 19:25
Hi @baywet Right now I have not applied any pro guard rule. But set of pro guard rules mentioned in the comments seems wrong to me. It has -keep class com.microsoft.** { *; } which will keep all the classes and methods related to MS graph Java SDK even when I am not using it.
But I will update you with my findings.

**Comment by atulgpt** [comment] 2020-09-16 20:38
Hi @baywet tried and it didn't work as well. Anyway not sure why this should work as any way my release apk is getting generated but issue is coming in Test APK generation. This proguard rule doesn't get applied in Test APK generation. To apply it in Test APK, I have also used testProguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro' but this also didn't fixed the issue

**Comment by baywet** [comment] 2020-09-16 21:13
ok thanks for trying. Can you try increasing memory to 4096M please?

**Comment by baywet** [comment] 2020-09-16 21:16
also, can you profile the different "flavors" and (release and unit test) and upload the results here please? https://developer.android.com/studio/build/optimize-your-build#profile

**Comment by bsiegel** [comment] 2020-09-17 00:49
Hi @atulgpt, my colleagues and I have been looking into this issue and have a few observations. First, in your posted gradle config (and in the linked sample app), the optimization settings for release & debug variants are opposite from what we would expect. Generally, optimization settings like `crunchPngs`, `minifyEnabled`, and `shrinkResources` are enabled in the release variant only, but in your posted config they are enabled for the debug variant, and disabled for the release variant. Was this intended? If not, setting `minifyEnabled` to false for the debug variant will avoid this issue, because the issue only occurs when trying to shrink the debugAndroidTest package. (And consider setting it to true for your release variant to remove dead code from your release builds.)

Second, we observed that this behavior only occurs when building with JDK8. If you do in fact need to build your debugAndroidTest package with shrinking enabled, switching the build JDK (File > Project Structure > SDK Location) to a newer version such as JDK11 should resolve the issue.

**Comment by atulgpt** [comment] 2020-09-17 11:31
Hi Regarding opposite config in build variants, this is only case in the demo project. In our actual set-up we do run R8(and all resource optimisation) on release builds as well. Regarding running automation with R8 on, this is our intended behaviour as running automation with R8 on also catches any bugs due to wrong R8 rules.

**Comment by atulgpt** [comment] 2020-09-17 17:33
Hi @bsiegel my project worked with JDK 13(at this time only JDK 13 is installed on my system apart from JDK 1.8) but this only solves the problem in my local but in my actual project I have no control over the JDK over which my project is compiled. Also since the it is pretty big project it is not possible to migrate to JDK 11. Also this also not recommended as per the Android Doc as they suggest to use pre bundled JDK for the Android Development

**Comment by bsiegel** [comment] 2020-09-17 17:43
We don't have a root cause just yet, but the current theory is that the combination of loading all of the code for the application and its other dependencies + the msgraph library and its dependencies + the test instrumentation code, all into the R8 shrinker at the same time is too much for the allotted memory, causing the GC to continually attempt to generate free memory. Newer JDKs have a more advanced GC, which appears to avoid this problem. This theory is bolstered by the observation that increasing the memory limit to 8GB does allow the shrinker to eventually succeed under JDK8 without running out of memory, although it takes quite a while. So if you aren't able to use a newer JDK for your builds, you can increase the memory allocated to the JDK8 build process and it will get you past this hurdle - modify the following build flags in your `gradle.properties` file: `org.gradle.jvmargs=-Xmx8192m -XX:MaxPermSize=8192m`

**Comment by anuchandy** [comment] 2020-09-17 18:13
To add to the point "advanced GC", if we switch default Java8 GC to G1GC, the test APK seems to get produced with the same memory settings, though we still found it very slow even with this GC.

Below given the updated build flag to switch GC.

```
org.gradle.jvmargs=-Xmx4096m -XX:MaxPermSize=512m -XX:+UseG1GC -Dfile.encoding=UTF-8
```

quick reference to [GCs](https://docs.microsoft.com/en-us/azure/developer/java/fundamentals/reasons-to-move-to-java-11#garbage-collection-10).

**Comment by atulgpt** [comment] 2020-09-22 08:23
Hi @bsiegel I have tried with new GC but that alone didn't fixe the error but with increased memory(8 GB) and new GC is running perfect in CI of my local branch. If these settings also fixes the error for main branch(as in main branch some more Gradle tasks run) then I will revert to you and then we may close this issue

**Comment by atulgpt** [comment] 2020-09-22 18:53
Hi @bsiegel now I verified the above mentioned solution in my CI server and everything working fine. Thanks for such a prompt response here

**Comment by baywet** [comment] 2020-09-22 19:04
this is great news! closing the issue

**Closed by baywet** 2020-09-22 19:04 UTC
Labels: Needs: Attention :wave:, question
