### ISSUE TITLE
How to access Microsoft Graph Java API from Java application behind a proxy server?

### ISSUE THREAD

**Issue by abhis-hd** [microsoftgraph/msgraph-sdk-java#162] opened 2018-11-04 18:42 UTC
Expected behavior
Is there a way to provide proxy server configuration(proxy server url, username, password etc.) while accessing Microsoft Graph Java API from Java application behind a proxy server?
Actual behavior
We are using MS graph Java sdk in order to access O365 ODFB drives from our java application. When I am bypassing the enterprise proxy server(connected to open internet) then I am able to get desired response from the APIs. But when I am connecting via proxy server, I am getting the following exception:
SEVERE: Throwable detail: com.microsoft.graph.core.ClientException: Error during http request Exception in thread "main" com.microsoft.graph.core.ClientException: Error during http request at com.microsoft.graph.http.DefaultHttpProvider.sendRequestInternal(DefaultHttpProvider.java:356) at com.microsoft.graph.http.DefaultHttpProvider.send(DefaultHttpProvider.java:197) at com.microsoft.graph.http.DefaultHttpProvider.send(DefaultHttpProvider.java:177) at com.microsoft.graph.http.BaseCollectionRequest.send(BaseCollectionRequest.java:87) at com.microsoft.graph.requests.generated.BaseDriveItemCollectionRequest.get(BaseDriveItemCollectionRequest.java:54) at com.example.TestMain.main(TestMain.java:148) Caused by: java.net.ConnectException: Connection timed out: connect at java.net.DualStackPlainSocketImpl.connect0(Native Method) at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source) at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source) at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source) at java.net.AbstractPlainSocketImpl.connect(Unknown Source) at java.net.PlainSocketImpl.connect(Unknown Source) at java.net.SocksSocketImpl.connect(Unknown Source) at java.net.Socket.connect(Unknown Source) at sun.security.ssl.SSLSocketImpl.connect(Unknown Source) at sun.security.ssl.BaseSSLSocketImpl.connect(Unknown Source) at sun.net.NetworkClient.doConnect(Unknown Source) at sun.net.www.http.HttpClient.openServer(Unknown Source) at sun.net.www.http.HttpClient.openServer(Unknown Source) at sun.net.www.protocol.https.HttpsClient.<init>(Unknown Source) at sun.net.www.protocol.https.HttpsClient.New(Unknown Source) at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(Unknown Source) at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(Unknown Source) at sun.net.www.protocol.http.HttpURLConnection.plainConnect(Unknown Source) at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(Unknown Source) at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source) at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source) at java.net.HttpURLConnection.getResponseCode(Unknown Source) at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(Unknown Source) at com.microsoft.graph.http.UrlConnection.getResponseCode(UrlConnection.java:110) at com.microsoft.graph.http.DefaultHttpProvider.sendRequestInternal(DefaultHttpProvider.java:297)
I already asked a question with same title at stackoverflow:
https://stackoverflow.com/questions/53079388/how-to-access-microsoft-graph-java-api-from-java-application-behind-a-proxy-serv
Steps to reproduce the behavior
Try to access Graph Java SDK APIs behind a proxy server which requires authentication.
[AB#6049](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/6049)

**Comment by deepak2016** [comment] 2018-11-14 11:22
You should be able to use proxy by specifying https.proxyHost and https.proxyPort.
We are currently experimenting with using the Apache HttpClient to bring interceptor support within the SDK. As part of this work we will ensure that being able to set the proxy is something that is easy to do.

**Comment by selimelawwa** [comment] 2019-04-18 15:43
@deepak2016  Have you made any progress in using to use Apache HttpClient within Microsoft Graph SDK to authenticate with username / password instead of client-id/ access token approach?
something similar to [Authentication to SharePoint from Java with username/password](https://stackoverflow.com/a/29609502/8863925)

**Comment by ingoschaefer** [comment] 2019-05-16 11:54
@deepak2016  - I already asked in issue https://github.com/microsoftgraph/msgraph-sdk-java/issues/158 the same question as @selimelawwa -- how is the progress with Apache HttpClient integration?

And if it takes too long, maybe one could add support for openConnection(Proxy) in the URLConnection class? Just like the support for the timeouts is built in.

Regards,
Ingo

**Comment by NakulSabharwal** [comment] 2019-05-20 04:12
@ingoschaefer and  @selimelawwa We are currently using OkHttp and not going with Apache HttpClient. Will let you know how you will be able to use proxy server with it. The java core we built is using OkHttp - https://github.com/microsoftgraph/msgraph-sdk-java-core and current repo will be integrated to use this core for making http calls.

**Comment by Samhithgb** [comment] 2019-09-16 08:54
@NakulSabharwal Is there any way now to setup proxy server for SDK requests? We are facing the same issue.

**Comment by ssimm** [comment] 2019-09-20 16:44
Hey folks.  This is annoying me too.  So I put a bounty on abhis-hd's question over on Stackoverflow.

**Comment by omerb4** [comment] 2020-01-27 16:06
Can anyone update on this issue? will it be prioritized soon?

**Comment by kavitha1051** [comment] 2020-04-08 07:05
Ca anyone help to resolve the below issue

Apr 08, 2020 12:11:38 PM com.microsoft.graph.logger.DefaultLogger logError
SEVERE: CoreHttpProvider[send] - 204Error during http request
Apr 08, 2020 12:11:38 PM com.microsoft.graph.logger.DefaultLogger logError
SEVERE: Throwable detail: com.microsoft.graph.core.ClientException: Error during http request
Exception in thread "main" com.microsoft.graph.core.ClientException: Error during http request

**Comment by kavitha1051** [comment] 2020-04-16 07:45
any update on this

**Comment by culmat** [comment] 2020-05-20 15:28
You can use the following hack around 
```
void setProxy(Proxy proxy, IGraphServiceClient graphClient) {
		CoreHttpProvider prov = (CoreHttpProvider) graphClient.getHttpProvider();
		
		IConnectionConfig connectionConfig = prov.getConnectionConfig();
		
		OkHttpClient.Builder okBuilder = HttpClients.createDefault(new ICoreAuthenticationProvider() {
			@Override
			public Request authenticateRequest(Request request) {
				return request;
			}
		}).newBuilder();
		
		okBuilder
		.proxy(proxy)
		.connectTimeout(connectionConfig.getConnectTimeout(), TimeUnit.MILLISECONDS)
		.readTimeout(connectionConfig.getReadTimeout(), TimeUnit.MILLISECONDS)
		.followRedirects(false)
		.retryOnConnectionFailure(false);
		
		try {
			FieldUtils.writeField(prov, "corehttpClient", okBuilder.build(), true);
		} catch (IllegalAccessException e) {
			throw new IllegalStateException(e);
		}
	}
```

a solution would be a pull request changing https://github.com/microsoftgraph/msgraph-sdk-java/blob/dev/src/main/java/com/microsoft/graph/http/CoreHttpProvider.java#L244

or simply a setter for the private field `OkHttpClient corehttpClient`

**Comment by omerb4** [comment] 2020-05-21 08:02
I did something like that:
![image](https://user-images.githubusercontent.com/15855765/82537331-8d643680-9b52-11ea-825b-7b592b59f934.png)

**Comment by rafher** [comment] 2020-05-29 07:09
Hi,
I modified the CoreHTtpProvider class and I included the lines 275 and 277. You can see it in the image. 
With this I have managed to get the requests to go out through the proxy, but now I have another problem, the requests return the following error:
```
CoreHttpProvider[send] - 219Graph service exception Error code: InvalidAuthenticationToken
CoreHttpProvider[send] - 219Error message: CompactToken parsing failed with error code: 80049217
CoreHttpProvider[send] - 219
 CoreHttpProvider[send] - 219GET https://graph.microsoft.com/v1.0/drive/root
CoreHttpProvider[send] - 219SdkVersion : graph-java/v1.7.1
 CoreHttpProvider[send] - 219Authorization : Bearer null
CoreHttpProvider[send] - 219
CoreHttpProvider[send] - 219
CoreHttpProvider[send] - 219401 : Unauthorized
```
Any idea?
![grapg](https://user-images.githubusercontent.com/541510/83231547-f1f34700-a18b-11ea-97e6-9ddd46a9a2a0.png)

**Comment by darrelmiller** [comment] 2020-09-22 13:34
We have work to do here, but customizing a OkHttp client is supposed to be possible and should be usable with the GraphClient.  Examples of how it should work from other languages are here https://docs.microsoft.com/en-us/graph/sdks/customize-client?context=graph%2Fapi%2F1.0&view=graph-rest-1.0&tabs=csharp   // @baywet

**Comment by baywet** [comment] 2020-09-24 18:29
Hi everyone,
Thanks for the feedback and thanks for the patience on the matter.
I have authored multiple PR's to address this issue:
- https://github.com/microsoftgraph/msgraph-sdk-java-core/pull/78 fixes multiple issues where the configuration of the httpclient could be partial/incomplete in some cases.
- #501 : adds the ability to configure and inject the http client in the graph service client
- https://github.com/microsoftgraph/microsoft-graph-docs/pull/10043 updates the documentation to show you how to configure the httpClient.

At this time the API I added is not optimal (you've probably noticed that it requires passing the authentication provider multiple time), this is something we'll clean up whenever we replace the current authentication stack by azure-identity.

Merging the pull requests will close this issue.

**Closed** 2020-09-28 15:04 UTC
Labels: enhancement, fixed, promote

**Comment by ashish26041992** [comment] 2021-01-20 11:56
Thanks a lot. it really helps but i have question how to set authenticated proxy ?
The below line does not have any username and password. it is having only hostname and port. 
Proxy proxy = new Proxy(Proxy.Type.HTTP, new InetSocketAddress("Ip", port));

**Comment by baywet** [comment] 2021-01-20 13:10
@ashish26041992 have you come across this post? https://stackoverflow.com/questions/35554380/okhttpclient-proxy-authentication-how-to

**Comment by kuehnse** [comment] 2021-01-22 15:41
Hi, my Java application is running on a server where the configured DNS server only resolves local addresses. I configured a proxy with authentication, but I am getting the following error, when executing SDK requests:
`
org.apache.oltu.oauth2.common.exception.OAuthSystemException: java.net.UnknownHostException: login.microsoftonline.com
at org.apache.oltu.oauth2.client.URLConnectionClient.execute(URLConnectionClient.java:108)
	at org.apache.oltu.oauth2.client.OAuthClient.accessToken(OAuthClient.java:65)
	at org.apache.oltu.oauth2.client.OAuthClient.accessToken(OAuthClient.java:55)
at org.apache.oltu.oauth2.client.OAuthClient.accessToken(OAuthClient.java:71)
`

On servers with DNS server configured for external lookups, my code works fine.
Is there a way to tell the SDK to send DNS requests to the configured proxy?

**Comment by baywet** [comment] 2021-01-22 17:04
Hi @kuehnse 
That's because the http client for the [authentication provider](https://github.com/microsoftgraph/msgraph-sdk-java-auth) does not have it's http proxy configured.
I'm not sure how you'd do that as the [http client](https://github.com/microsoftgraph/msgraph-sdk-java-auth/blob/dev/src/main/java/com/microsoft/graph/auth/confidentialClient/ClientCredentialProvider.java) is not exposed.

I think that your two options are:
- implement your own authentication provider
- wait for the release of the v3 of the SDK, which provide a whole new authentication stack base off azure-identity.

**Comment by kuehnse** [comment] 2021-01-25 06:38
Thank you @baywet.
Do you have an ETA for the release of v3?

**Comment by baywet** [comment] 2021-01-25 13:46
We're updating the milestone here. The current date will probably slide another week though, there are a few additional things we want to get in last minute. https://github.com/microsoftgraph/msgraph-sdk-java/milestone/4

**Comment by baywet** [comment] 2021-01-25 13:47
The release is conditional to finishing the work in this milestone as well. https://github.com/microsoftgraph/msgraph-sdk-java-core/milestone/2

Quick question: would you be interested in trying a preview of the new version 3?

**Comment by giancanuz** [comment] 2021-01-25 14:13
@baywet thank you for support, I arrange my own authentication provider by extending the UsernamePasswordProvider from graph-oauth library. 
Since I am testing a POC for proxy, I decided to using the same OkHttpClient for both authentication provider and graphclient.
Don't know if it is the best approch but it seems promising to me.

Anyway, it would be great if I can have a look on version 3 preview source code

**Comment by baywet** [comment] 2021-01-25 14:17
You can follow the ongoing progress here https://github.com/microsoftgraph/msgraph-sdk-java/pull/522 and here https://github.com/microsoftgraph/msgraph-sdk-java-core/pull/87

**Comment by baywet** [comment] 2021-01-25 14:18
I'll bump the version numbers and publish snapshots later this week so you can import the preview versions without having to build it yourselves

**Comment by kuehnse** [comment] 2021-01-25 14:27
Thank you, I would also like to test v3 preview

**Comment by kuehnse** [comment] 2021-02-18 10:20
I just tested v3, but I have still the same issue with DNS requests not being sent to the configured proxy. This is my code:
```
final UsernamePasswordCredential usernamePasswordCredential = new UsernamePasswordCredentialBuilder()
                    .clientId(clientId)
                    .username(username)
                    .password(password)
                    .build();
final TokenCredentialAuthProvider authProvider = new TokenCredentialAuthProvider(usernamePasswordCredential);

Proxy proxy = new Proxy(Proxy.Type.HTTP, new InetSocketAddress(proxyUrl, proxyPort));
Authenticator proxyAuthenticator = (route, response) -> {
                String credential = Credentials.basic(proxyUser, proxyPassword);
                return response.request().newBuilder()
                        .header("Proxy-Authorization", credential)
                        .build();
            };

final OkHttpClient httpClient = HttpClients.createDefault(authProvider)
                    .newBuilder()
                    .proxy(proxy)
                    .proxyAuthenticator(proxyAuthenticator)
                    .build();

final GraphServiceClient graphClient = GraphServiceClient.builder()
                    .httpClient(httpClient)
                    .authenticationProvider(authProvider)
                    .buildClient();

final User user = graphClient.me().buildRequest().get();
```

The log shows:
```
ERROR [ForkJoinPool.commonPool-worker-1] com.microsoft.aad.msal4j.PublicClientApplication: [Correlation ID: XXX] Execution of class com.microsoft.aad.msal4j.AcquireTokenByAuthorizationGrantSupplier failed.
com.microsoft.aad.msal4j.MsalClientException: java.lang.RuntimeException: Max retries 3 times exceeded. Error Details: login.microsoftonline.com
	at com.microsoft.aad.msal4j.HttpHelper.executeHttpRequest(HttpHelper.java:68)
	at com.microsoft.aad.msal4j.UserDiscoveryRequest.execute(UserDiscoveryRequest.java:30)
	at com.microsoft.aad.msal4j.AcquireTokenByAuthorizationGrantSupplier.processPasswordGrant(AcquireTokenByAuthorizationGrantSupplier.java:91)
	at com.microsoft.aad.msal4j.AcquireTokenByAuthorizationGrantSupplier.execute(AcquireTokenByAuthorizationGrantSupplier.java:43)
	at com.microsoft.aad.msal4j.AuthenticationResultSupplier.get(AuthenticationResultSupplier.java:59)
	at com.microsoft.aad.msal4j.AuthenticationResultSupplier.get(AuthenticationResultSupplier.java:17)
...
Caused by: java.net.UnknownHostException: login.microsoftonline.com
```

Does anyone have an idea? Am I missing something?

**Comment by baywet** [comment] 2021-02-18 13:45
thanks for sharing the solution with others!

**Comment by sujitjadhav07** [comment] 2021-03-22 12:36
@kuehnse @baywet 

Thanka for providing the solution.
However it doesnt seem to work for me. Im using the ClientCredentials approach, but end up getting below error.

2021-03-22T16:04:18,295 ERROR [restartedMain] o.s.b.SpringApplication: Application run failed
java.lang.BootstrapMethodError: java.lang.NoClassDefFoundError: reactor/netty/tcp/ProxyProvider$TypeSpec
    at com.azure.core.http.netty.NettyAsyncHttpClientBuilder.lambda$build$7(NettyAsyncHttpClientBuilder.java:142)
    at reactor.netty.http.client.HttpClient.tcpConfiguration(HttpClient.java:1343)
    at com.azure.core.http.netty.NettyAsyncHttpClientBuilder.build(NettyAsyncHttpClientBuilder.java:122)
    at com.azure.core.http.netty.NettyAsyncHttpClientProvider.createInstance(NettyAsyncHttpClientProvider.java:32)
    at com.azure.core.implementation.http.HttpClientProviders.createInstance(HttpClientProviders.java:48)
    at com.azure.core.http.HttpClient.createDefault(HttpClient.java:50)
    at com.app.intune.config.GraphClient.getGraphServiceClient(GraphClient.java:48)
    at com.app.intune.util.UserUtil.getUsersWithRegisteredDevicesAndSave(UserUtil.java:140)
    at com.app.intune.IntuneApplication.run(IntuneApplication.java:61)
    at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:804)
    at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:788)
    at org.springframework.boot.SpringApplication.run(SpringApplication.java:333)
    at com.app.intune.IntuneApplication.main(IntuneApplication.java:56)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:49)
Caused by: java.lang.NoClassDefFoundError: reactor/netty/tcp/ProxyProvider$TypeSpec
    ... 18 more
Caused by: java.lang.ClassNotFoundException: reactor.netty.tcp.ProxyProvider$TypeSpec
    at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 18 more

More details at link[link](https://stackoverflow.com/questions/66744821/ms-graph-3-0-java-clientcredentials-error-java-lang-bootstrapmethoderror-jav)

**Comment by baywet** [comment] 2021-03-22 12:40
@sujitjadhav07 
Thanks for reaching out. This seems to be an issue with Azure Identity. Can you check on [this repo](https://github.com/Azure/azure-sdk-for-java/) whether you find a similar issue, and create a new one if you can't find anything? Don't hesitate to link back here.

**Comment by sujitjadhav07** [comment] 2021-03-22 17:13
@baywet Thanks for responding. Before i try the repo mentioned, had a couple of updates.
1. The microsoft-graph 3.0.0 works perfectly without spring boot.
2. If i include spring boot 2.4.1 or 2.4.4, i start getting NoClassDefFoundError errors. I managed to resolve the first error by setting <okhttp3.version>4.9.1</okhttp3.version> in pom.xml. But now im getting other NoClassDefFoundError.  (check update in stackoverflow.com).

Any guidance on how to use microsoft-graph 3.0 with spring boot. I had no problems with microsoft-graph 2.10.0 with spring boot 2.4.1.

**Comment by baywet** [comment] 2021-03-22 18:03
@sujitjadhav07 thanks for the additional details. My knowledge of spring boot is limited, is it possible they trim some packages that are not explicitly required in the manifest? You might want to check [the change notification sample](https://github.com/microsoftgraph/java-spring-webhooks-sample) which I have upgraded to v3, runs on spring boot and works fine.

**Comment by sujitjadhav07** [comment] 2021-03-24 08:32
@baywet Following are the additional updates.

I have managed to get ms graph 3.0 running with spring boot 2.4.4.
ms graph 3.0 has the dependency tree as below for reactor:
microsoft-graph : 3.0.0
 - microsoft-graph-core : 2.0.0
    - azure-identity :1.2.3
      - azure-core : 1.13.0
        - **reactor-core :3.3.12.RELEASE**
      - azure-core-http-netty : 1.8.0
        - **reactor-netty : 0.9.15.RELEASE**
 
Spring boot 2.4.4 has managed dependency of : 
reactor-core : **3.4.4**
reactor-netty : **1.0.5**

The new version of reactor-netty doesnt work for microsoft-graph 3.0. Hence i had to manually override it by adding the below in pom.xml.
<dependency>
<groupId>io.projectreactor.netty</groupId>
<artifactId>reactor-netty</artifactId>
<version>0.9.15.RELEASE</version>
</dependency>

Only overriding reactor-netty is required, Okhtp3 overriding is not required as mentioned in earlier comment.

**Comment by baywet** [comment] 2021-03-24 10:50
Thanks for sharing the details with the broader community @sujitjadhav07 
Would you mind opening an issue on the [azure Java SDK repo](https://github.com/Azure/azure-sdk-for-java) asking them to upgrade this dependency to latest because it's causing an issue with spring projects please? Thanks!

**Comment by SabbitRex** [comment] 2021-06-04 14:20
I still could not get this working for my proxy which is unathenticated. Below is the code that I wrote, I am getting "SocketTimeoutException" when I am trying to pass okHttpClient object to create **GraphServiceClient**. and then making a call using it.

The "if" is the configuration with proxy, which means I will use hostAddress and hostPort, and the "else" is non-proxy configuration.
`       
        if (this.proxy.equals("true")) {       
            
            final ClientSecretCredential clientSecretCredential = new ClientSecretCredentialBuilder()
                    .clientId(this.clientId)
                    .clientSecret(this.clientSecret)
                    .tenantId(this.b2cTenant)
                    .build();

            final TokenCredentialAuthProvider tokenCredentialAuthProvider = 
                new TokenCredentialAuthProvider(Constant.scopes, clientSecretCredential);
            
            final Proxy proxy = new Proxy(Proxy.Type.HTTP, new InetSocketAddress(this.hostAddress, this.hostPort));
            
            final OkHttpClient httpClient = HttpClients.createDefault(tokenCredentialAuthProvider)
                    .newBuilder()
                    .proxy(proxy)
                    .build();

            graphClient = GraphServiceClient.builder()
                    .authenticationProvider(tokenCredentialAuthProvider)
                    .httpClient(httpClient)
                    .buildClient();
            
        } else {
            
            final ClientSecretCredential clientSecretCredential = new ClientSecretCredentialBuilder()
                    .clientId(this.clientId)
                    .clientSecret(this.clientSecret)
                    .tenantId(this.b2cTenant)
                    .build();

            final TokenCredentialAuthProvider tokenCredentialAuthProvider = 
                new TokenCredentialAuthProvider(Constant.scopes, clientSecretCredential);
            
            graphClient = GraphServiceClient.builder()
                    .authenticationProvider(tokenCredentialAuthProvider)
                    .buildClient();
        }`

So now once I get **graphClient** from "if" (proxy enabled config)...I am using it like this...

I created a LinkedList of type "QueryOption" and I am trying to check if user is present in B2C AD by using issuerAssignedId.

But I am getting SocketTimeOutConnection. I dont know what I am doing wrong. 

`String queryTerm = "identities/any(c:c/issuerAssignedId eq '" + issuerAssignedId + "' and c/issuer eq '" + b2cTenant + "')";

        requestOptions.add(new QueryOption("$filter", queryTerm));
        
        UserCollectionPage userCollection = graphClient.users()
                .buildRequest(requestOptions)
                .get();

        List<User> userInfoList = userCollection.getCurrentPage();
        
        if (userInfoList.size() == 0) {
            System.out.println("User does not exist in given directory.");
        } else {
            System.out.println("User exists in given directory.");
        }`

I even tried to setup proxy at JVM level, i.e. 

`System.setProperty("java.net.useSystemProxies", "true");
           System.setProperty("http.proxyHost", host);  
           System.setProperty("http.proxyPort", port);`


@culmat @baywet @sujitjadhav07 please help. I am confused what am I doing wrong?

When I am running as non proxy, it is working fine.

**Comment by baywet** [comment] 2021-06-04 15:22
@SabbitRex with the configuration you have the proxy is set for the graph client but not for the authentication library. Have a look at this PR that shows how to set the proxy for both the graph client and the authentication library. https://github.com/microsoftgraph/microsoft-graph-docs/pull/12779
