### ISSUE TITLE
Application is stuck when trying to fetch files from root folder of drive in v 6.5.1

### ISSUE THREAD

**Issue by ihudedi** [microsoftgraph/msgraph-sdk-java#1911] opened 2024-04-01 14:24 UTC
Hi,
I  upgrade graph api to 6.5.1 and now when I run the following line the application is stuck
graphServiceClient.drives().byDriveId("DRIVE_ID").items().byDriveItemId("root").children().get()
When I was working in version 6.5.0 it was working fine.
The issue is with the kiota version 1.1.2
If I modifed the kiota abstraction to 1.1.1
 <dependency>
            <groupId>com.microsoft.kiota</groupId>
            <artifactId>microsoft-kiota-abstractions</artifactId>
            <version>1.1.1</version>
        </dependency>
It's working fine.
Thanks,
Itay

**Comment by vivekkothari** [comment] 2024-04-03 03:56
Seeing the same behaviour with calendar event delta requests.. and downgrading `kiota abstraction` to 1.1.1 solves it..

**Comment by ihudedi** [comment] 2024-04-07 08:25
Hi @baywet 
Any updates?
Seems the new version of microsoft-kiota-abstractions cause an issue?
Same issue in 1.1.3
Thanks,
Itay

**Comment by ihudedi** [comment] 2024-04-16 07:51
Any updates?

**Comment by paulwoods222** [comment] 2024-04-17 13:11
Same with outlook iterator -seems to be stuck in an infinite loop in the kiota library at InMemoryBackingStore.touchNestedProperties

**Comment by avnerw74** [comment] 2024-04-18 09:22
Hi @baywet, 

Is there any update about this? Is it planned to be fixed in 1.1.5? 
Currently, we must use 1.1.1 until the issue is fixed.

Thanks,
Avner

**Comment by paulwoods222** [comment] 2024-04-18 15:47
You are right, it's not in an infinite loop - just slowing down over time as each response comes in. It will eventually make progress from a call if you wait long enough.

A typical call stack for me looks like:
InMemoryBackingStore.enumerate:99	
InMemoryBackingStore.touchNestedProperties:242	
InMemoryBackingStore.ensureCollectionPropertyIsConsistent:234	
InMemoryBackingStore.getValueFromWrapper:119	
InMemoryBackingStore.enumerate:92	
InMemoryBackingStore.touchNestedProperties:242	
InMemoryBackingStore.ensureCollectionPropertyIsConsistent:234	
InMemoryBackingStore.setIsInitializationCompleted:65	
InMemoryBackingStore.setupNestedSubscriptions:204	
InMemoryBackingStore.set:148	
InMemoryBackingStore.lambda$setupNestedSubscriptions$1:207	
InMemoryBackingStore$$Lambda/0x000001ddb36e3b58.accept	
InMemoryBackingStore.set:173	
InMemoryBackingStore.ensureCollectionPropertyIsConsistent:228	
InMemoryBackingStore.setIsInitializationCompleted:65	
InMemoryBackingStore.setupNestedSubscriptions:204	
InMemoryBackingStore.set:148	
InMemoryBackingStore.lambda$setupNestedSubscriptions$1:207	
InMemoryBackingStore$$Lambda/0x000001ddb36e3b58.accept	
InMemoryBackingStore.set:173	
InMemoryBackingStore.ensureCollectionPropertyIsConsistent:228	
InMemoryBackingStore.setIsInitializationCompleted:65	
InMemoryBackingStore.setupNestedSubscriptions:204	
InMemoryBackingStore.set:148	
InMemoryBackingStore.lambda$setupNestedSubscriptions$1:207	
InMemoryBackingStore$$Lambda/0x000001ddb36e3b58.accept	
InMemoryBackingStore.set:173	
InMemoryBackingStore.ensureCollectionPropertyIsConsistent:228	
InMemoryBackingStore.setIsInitializationCompleted:65	
InMemoryBackingStore.setupNestedSubscriptions:204	
InMemoryBackingStore.set:148	
InMemoryBackingStore.lambda$setupNestedSubscriptions$1:207	
InMemoryBackingStore$$Lambda/0x000001ddb36e3b58.accept	
InMemoryBackingStore.set:173	
InMemoryBackingStore.ensureCollectionPropertyIsConsistent:228	
InMemoryBackingStore.setIsInitializationCompleted:65	
InMemoryBackingStore.setupNestedSubscriptions:204	
InMemoryBackingStore.set:148	
InMemoryBackingStore.lambda$setupNestedSubscriptions$1:207	
InMemoryBackingStore$$Lambda/0x000001ddb36e3b58.accept	
InMemoryBackingStore.set:173	
InMemoryBackingStore.ensureCollectionPropertyIsConsistent:228	
InMemoryBackingStore.setIsInitializationCompleted:65	
InMemoryBackingStore.setupNestedSubscriptions:204	
InMemoryBackingStore.set:148	
InMemoryBackingStore.lambda$setupNestedSubscriptions$1:207	
InMemoryBackingStore$$Lambda/0x000001ddb36e3b58.accept	
InMemoryBackingStore.set:173	
InMemoryBackingStore.ensureCollectionPropertyIsConsistent:228	
InMemoryBackingStore.setIsInitializationCompleted:65	
InMemoryBackingStore.setupNestedSubscriptions:204	
InMemoryBackingStore.set:148	
InMemoryBackingStore.lambda$setupNestedSubscriptions$1:207	
InMemoryBackingStore$$Lambda/0x000001ddb36e3b58.accept	
InMemoryBackingStore.set:173	
InMemoryBackingStore.ensureCollectionPropertyIsConsistent:228	
InMemoryBackingStore.setIsInitializationCompleted:65	
InMemoryBackingStore.setupNestedSubscriptions:204	
InMemoryBackingStore.set:148	
InMemoryBackingStore.lambda$setupNestedSubscriptions$1:207	
InMemoryBackingStore$$Lambda/0x000001ddb36e3b58.accept	
InMemoryBackingStore.set:173	
InMemoryBackingStore.ensureCollectionPropertyIsConsistent:228	
InMemoryBackingStore.getValueFromWrapper:119	
InMemoryBackingStore.enumerate:92	
InMemoryBackingStore.touchNestedProperties:242	
InMemoryBackingStore.ensureCollectionPropertyIsConsistent:223	
InMemoryBackingStore.setIsInitializationCompleted:65	
BackingStoreParseNodeFactory.lambda$new$1:31	
BackingStoreParseNodeFactory$$Lambda/0x000001ddb3516330.accept	
ParseNodeProxyFactory.lambda$getParseNode$1:54	
ParseNodeProxyFactory$$Lambda/0x000001ddb3542e98.accept	
JsonParseNode.assignFieldValues:303	
JsonParseNode.getObjectValue:214	
OkHttpRequestAdapter.send:300	
PageIterator.interpageIterate:249	
PageIterator.iterate:272	

The JSON is just a normal response for a page of emails - I would rather not post that publicly, it can easily be reproduced using the graph sdk.
I will do some captures tomorrow using fiddler, to get the timings with 1.1.1 and 1.1.3
Paul

**Comment by paulwoods222** [comment] 2024-04-19 09:17
Here is a minimum test case to reproduce the issue, run against a developer e5 instance.
 The code fetches all users and for licenced users it fetches all mail folders, then fetches all emails in those folders - and just counts them.
 Run using 6.5.1 of microsoft-graph-beta, just changing the kiota versions.
 
 Output:
 kiota 1.1.1  Fetched 1436 emails in 37s
 kiota 1.1.3  still running after 1/2 hour.
 
 
    private void iterateAllEmails(GraphServiceClient graphClient) {
        try {
            long start = System.currentTimeMillis();
            final AtomicLong totalMails = new AtomicLong();

            UserCollectionResponse userPage = graphClient.users().get();
            List<User> users = new ArrayList<>();
            iterateAndAddToCollection(graphClient, users, userPage, UserCollectionResponse::createFromDiscriminatorValue);
            for (User u : users) {
                if (!u.getAssignedLicenses().isEmpty()) {  //some users don't have mailboxes
                    System.out.println("process user " + u.getDisplayName());
                    List<MailFolder> folders = new ArrayList<>();
                    MailFolderCollectionResponse folderPage = graphClient.users().byUserId(u.getId()).mailFolders().get();
                    iterateAndAddToCollection(graphClient, folders, folderPage, MailFolderCollectionResponse::createFromDiscriminatorValue);
                    for (MailFolder folder : folders) {
                        MessageCollectionResponse page = graphClient.users().byUserId(u.getId()).mailFolders().byMailFolderId(folder.getId()).messages().get();
                        PageIterator<Message, MessageCollectionResponse> iter = new PageIterator.Builder<Message, MessageCollectionResponse>()
                                .client(graphClient)
                                .collectionPage(page)
                                .collectionPageFactory(MessageCollectionResponse::createFromDiscriminatorValue)
                                .processPageItemCallback(item -> {
                                    totalMails.incrementAndGet();
                                    return true;
                                })
                                .build();
                        iter.iterate();
                    }
                }
            }
            long timemillis = System.currentTimeMillis() - start;
            System.out.println("Fetched " + totalMails.get() + " emails in " + timemillis / 1000 + "s");
        } catch (Throwable ex) {
            System.err.println("oops " + ex.getMessage());
        }
    }


    private <T extends Parsable, V extends Parsable & AdditionalDataHolder>
            void iterateAndAddToCollection(GraphServiceClient graphClient, Collection<T> toFill, V holder, ParsableFactory<V> m) throws InvocationTargetException, IllegalAccessException, NoSuchMethodException, ApiException, ReflectiveOperationException {

        PageIterator<T, V> iter = new PageIterator.Builder<T, V>()
                .client(graphClient)
                .collectionPage(holder)
                .collectionPageFactory(m)
                .processPageItemCallback(item -> {
                    toFill.add(item);
                    return true;
                })
                .build();
        iter.iterate();

    }

**Comment by etcoyvindf** [comment] 2024-04-23 06:01
Thanks for linking this issue to mine. @baywet . I would never have guessed they were related.

I'm trying to produce an example of a JSON response that can reproduce the problem. I am now however getting stuck on Azure Identity Authentication Provider trying to parse the token response from `https://login.microsoftonline.com/<uuid>/oauth2/v2.0/token`. 

Since Kiota 1.1.6 has been released, I tried to use both 1.1.5 and 1.1.6.

It's getting stuck in azure-identity-1.12.0.jar HttpPipelineAdapter method parseJsonInto map. the loop is waiting for currentToken == END_OBJECT but jsonParser.nextToken() sets the token to null, which is never checked. 

If this is related at all or not I do not know, but it seems to me that this parsing is lacking some infinite loop protection.
The start of the logged response is `HTTP response","contentLength":"1708","statusCode":200,"url":"https://login.microsoftonline.com/<tenantid>/oauth2/v2.0/token","durationMs":139,"body":"{\"token_type\":\"Bearer\",\"expires_in\":3599,\"ext_expires_in\":3....` and it does seem to be a complete JSON response.

Trying to authenticate against another tenant (with another secret) works just fine, and this produces a JSON that does get stuck. This was against the users().delta().get() request, so I'd needto anonymize the JSON before sharing it here. Let me know if this is at all helpful.

**Comment by papegaaij** [comment] 2024-04-23 09:54
We've hit this same issue. For now, we're using a patched version of kiota-abstractions with the changes from https://github.com/microsoft/kiota-java/pull/1142 reverted. This fixes our issue. It seems `InMemoryBackingStore` gets stuck in some endless (and probably recursive) loop. Here is a fragment from the stacktrace. You can already see the repeating pattern. The stacktrace is much longer, but it keeps repeating the same 7 frames. We hit this problem simply by reading groups. We only specify a filter, nothing else.

{code}
deployment.keyhub-ear.ear.keyhub-rest.war//com.microsoft.kiota.store.InMemoryBackingStore.set(InMemoryBackingStore.java:148)
deployment.keyhub-ear.ear.keyhub-rest.war//com.microsoft.kiota.store.InMemoryBackingStore.lambda$setupNestedSubscriptions$1(InMemoryBackingStore.java:207)
deployment.keyhub-ear.ear.keyhub-rest.war//com.microsoft.kiota.store.InMemoryBackingStore$$Lambda$3735/0x00000008034ad8f0.accept(Unknown Source)
deployment.keyhub-ear.ear.keyhub-rest.war//com.microsoft.kiota.store.InMemoryBackingStore.set(InMemoryBackingStore.java:173)
deployment.keyhub-ear.ear.keyhub-rest.war//com.microsoft.kiota.store.InMemoryBackingStore.ensureCollectionPropertyIsConsistent(InMemoryBackingStore.java:228)
deployment.keyhub-ear.ear.keyhub-rest.war//com.microsoft.kiota.store.InMemoryBackingStore.setIsInitializationCompleted(InMemoryBackingStore.java:65)
deployment.keyhub-ear.ear.keyhub-rest.war//com.microsoft.kiota.store.InMemoryBackingStore.setupNestedSubscriptions(InMemoryBackingStore.java:204)
deployment.keyhub-ear.ear.keyhub-rest.war//com.microsoft.kiota.store.InMemoryBackingStore.set(InMemoryBackingStore.java:148)
deployment.keyhub-ear.ear.key﻿hub-rest.war//com.microsoft.kiota.store.InMemoryBackingStore.lambda$setupNestedSubscriptions$1(InMemoryBackingStore.java:207)
deployment.keyhub-ear.ear.keyhub-rest.war//com.microsoft.kiota.store.InMemoryBackingStore$$Lambda$3735/0x00000008034ad8f0.accept(Unknown Source)
deployment.keyhub-ear.ear.keyhub-rest.war//com.microsoft.kiota.store.InMemoryBackingStore.set(InMemoryBackingStore.java:173)
deployment.keyhub-ear.ear.keyhub-rest.war//com.microsoft.kiota.store.InMemoryBackingStore.ensureCollectionPropertyIsConsistent(InMemoryBackingStore.java:228)
deployment.keyhub-ear.ear.keyhub-rest.war//com.microsoft.kiota.store.InMemoryBackingStore.setIsInitializationCompleted(InMemoryBackingStore.java:65)
deployment.keyhub-ear.ear.keyhub-rest.war//com.microsoft.kiota.store.InMemoryBackingStore.setupNestedSubscriptions(InMemoryBackingStore.java:204)
deployment.keyhub-ear.ear.keyhub-rest.war//com.microsoft.kiota.store.InMemoryBackingStore.set(InMemoryBackingStore.java:148)
deployment.keyhub-ear.ear.keyhub-rest.war//com.microsoft.kiota.store.InMemoryBackingStore.lambda$setupNestedSubscriptions$1(InMemoryBackingStore.java:207)
deployment.keyhub-ear.ear.keyhub-rest.war//com.microsoft.kiota.store.InMemoryBackingStore$$Lambda$3735/0x00000008034ad8f0.accept(Unknown Source)
deployment.keyhub-ear.ear.keyhub-rest.war//com.microsoft.kiota.store.InMemoryBackingStore.set(InMemoryBackingStore.java:173)
deployment.keyhub-ear.ear.keyhub-rest.war//com.microsoft.kiota.store.InMemoryBackingStore.ensureCollectionPropertyIsConsistent(InMemoryBackingStore.java:228)
deployment.keyhub-ear.ear.keyhub-rest.war//com.microsoft.kiota.store.InMemoryBackingStore.setIsInitializationCompleted(InMemoryBackingStore.java:65)
deployment.keyhub-ear.ear.keyhub-rest.war//com.microsoft.kiota.store.InMemoryBackingStore.setupNestedSubscriptions(InMemoryBackingStore.java:204)
deployment.keyhub-ear.ear.keyhub-rest.war//com.microsoft.kiota.store.InMemoryBackingStore.set(InMe﻿moryBackingStore.java:148)
deployment.keyhub-ear.ear.keyhub-rest.war//com.microsoft.kiota.store.InMemoryBackingStore.lambda$setupNestedSubscriptions$1(InMemoryBackingStore.java:207)
deployment.keyhub-ear.ear.keyhub-rest.war//com.microsoft.kiota.store.InMemoryBackingStore$$Lambda$3735/0x00000008034ad8f0.accept(Unknown Source)
deployment.keyhub-ear.ear.keyhub-rest.war//com.microsoft.kiota.store.InMemoryBackingStore.set(InMemoryBackingStore.java:173)
deployment.keyhub-ear.ear.keyhub-rest.war//com.microsoft.kiota.store.InMemoryBackingStore.ensureCollectionPropertyIsConsistent(InMemoryBackingStore.java:228)
deployment.keyhub-ear.ear.keyhub-rest.war//com.microsoft.kiota.store.InMemoryBackingStore.setIsInitializationCompleted(InMemoryBackingStore.java:65)
deployment.keyhub-ear.ear.keyhub-rest.war//com.microsoft.kiota.store.InMemoryBackingStore.setupNestedSubscriptions(InMemoryBackingStore.java:204)
deployment.keyhub-ear.ear.keyhub-rest.war//com.microsoft.kiota.store.InMemoryBackingStore.set(InMemoryBackingStore.java:148)
deployment.keyhub-ear.ear.keyhub-rest.war//com.microsoft.kiota.store.InMemoryBackingStore.lambda$setupNestedSubscriptions$1(InMemoryBackingStore.java:207)
deployment.keyhub-ear.ear.keyhub-rest.war//com.microsoft.kiota.store.InMemoryBackingStore$$Lambda$3735/0x00000008034ad8f0.accept(Unknown Source)
deployment.keyhub-ear.ear.keyhub-rest.war//com.microsoft.kiota.store.InMemoryBackingStore.set(InMemoryBackingStore.java:173)
deployment.keyhub-ear.ear.keyhub-rest.war//com.microsoft.kiota.store.InMemoryBackingStore.ensureCollectionPropertyIsConsistent(InMemoryBackingStore.java:228)
deployment.keyhub-ear.ear.keyhub-rest.war//com.microsoft.kiota.store.InMemoryBackingStore.getValueFromWrapper(InMemoryBackingStore.java:119)
deployment.keyhub-ear.ear.keyhub-rest.war//com.microsoft.kiota.store.InMemoryBackingStore.enumerate(InMemoryBackingStore.java:92)
deployment.keyhub-ear.ear.keyhub-rest.war//com.microsoft.kiota.sto﻿re.InMemoryBackingStore.touchNestedProperties(InMemoryBackingStore.java:242)
deployment.keyhub-ear.ear.keyhub-rest.war//com.microsoft.kiota.store.InMemoryBackingStore.ensureCollectionPropertyIsConsistent(InMemoryBackingStore.java:223)
deployment.keyhub-ear.ear.keyhub-rest.war//com.microsoft.kiota.store.InMemoryBackingStore.setIsInitializationCompleted(InMemoryBackingStore.java:65)
deployment.keyhub-ear.ear.keyhub-rest.war//com.microsoft.kiota.store.BackingStoreParseNodeFactory.lambda$new$1(BackingStoreParseNodeFactory.java:31)
deployment.keyhub-ear.ear.keyhub-rest.war//com.microsoft.kiota.store.BackingStoreParseNodeFactory$$Lambda$3597/0x00000008033808e8.accept(Unknown Source)
deployment.keyhub-ear.ear.keyhub-rest.war//com.microsoft.kiota.serialization.ParseNodeProxyFactory.lambda$getParseNode$1(ParseNodeProxyFactory.java:54)
deployment.keyhub-ear.ear.keyhub-rest.war//com.microsoft.kiota.serialization.ParseNodeProxyFactory$$Lambda$3645/0x00000008033ecf90.accept(Unknown Source)
deployment.keyhub-ear.ear.keyhub-rest.war//com.microsoft.kiota.serialization.JsonParseNode.assignFieldValues(JsonParseNode.java:303)
deployment.keyhub-ear.ear.keyhub-rest.war//com.microsoft.kiota.serialization.JsonParseNode.getObjectValue(JsonParseNode.java:214)
deployment.keyhub-ear.ear.keyhub-rest.war//com.microsoft.kiota.http.OkHttpRequestAdapter.send(OkHttpRequestAdapter.java:300)
deployment.keyhub-ear.ear.keyhub-rest.war//com.microsoft.graph.groups.GroupsRequestBuilder.get(GroupsRequestBuilder.java:120){code}

**Closed** 2024-04-23 14:40 UTC
Labels: bug
