### ISSUE TITLE
Casting/creating specific sub classes of directory objects

### ISSUE THREAD

**Issue by mriegler** [microsoftgraph/msgraph-sdk-java#232] opened 2019-03-20 16:30 UTC
Getting, for example, the transitive members of a group returns lists of directory objects. I can filter them based on the oDataType property. How do I cast or create this specific subclass from that object?

Rough example:
```

for (DirectoryObject d : currentPage) {
  if (d.oDataType.equals("user")) {
    User u = ?????;
  }
}

```

**Comment by davidmoten** [comment] 2020-02-09 23:48
From memory you need to get the id of the DirectoryObject and make another call to the api requesting a User specifically OR interrogate the raw json associated with the DirectoryObject for the bit you want. Ugly!

**Comment by davidmoten** [comment] 2020-02-09 23:57
See #154

**Comment by baywet** [comment] 2020-09-01 12:27
closing as duplicate of #154

**Closed by baywet** 2020-09-01 12:27 UTC
