### ISSUE TITLE
graphServiceClient.users(userId).photo().getContent().buildRequest().put(imageBytes) throws java.lang.ClassCastException

### ISSUE THREAD

**Issue by Krisoblucki-okta** [microsoftgraph/msgraph-sdk-java#176] opened 2018-12-11 00:58 UTC
### Expected behavior

graphServiceClient.users(userId).photo().getContent().buildRequest().put(imageBytes) should not throw an invalid cast exception from BufferedInputStream to ProfilePhoto

### Actual behavior

java.lang.ClassCastException: java.io.BufferedInputStream cannot be cast to com.microsoft.graph.models.extensions.ProfilePhoto

### Steps to reproduce the behavior

graphServiceClient.users(userId).photo().getContent().buildRequest().put(imageBytes)

**Comment by Krisoblucki-okta** [comment] 2018-12-12 01:01
What is the path for a fix to something like this which doesn't fit into the extensions?  I submitted a PR to what the fix could be.  I realize that's not how it works due to the change uptake mechanism.

**Comment by deepak2016** [comment] 2018-12-12 05:43
@Krisoblucki-okta thanks for reporting your issue, wanted to understand what scenario you are trying to achieve?

**Comment by Krisoblucki-okta** [comment] 2018-12-12 16:10
I'm trying to do a straight forward profile photo update

**Comment by Krisoblucki-okta** [comment] 2019-04-18 17:40
@deepak2016 since this is still open, I'm assuming that the issue hasn't been addressed?

**Comment by DanielWebelsiep** [comment] 2019-11-20 17:13
The bug still exists in 1.7.1 release, when you try to set a phone on a contact. 
graphServiceClient.me().contacts(contactId).photo().content().buildRequest().put(pictureContent)

**Comment by tiagodiogo** [comment] 2020-04-22 10:48
I recently encountered this bug, from my investigation I belive the problem is that the response is a no content with text/plain? 
this causes a problem on the httpprovider since everything that is not text/json is assumed to be binary. my fix was:

`final String contentType = headers.get(Constants.CONTENT_TYPE_HEADER_NAME);
                if (contentType.contains(Constants.JSON_CONTENT_TYPE)) {
                    logger.logDebug("Response json");
                    return handleJsonResponse(in, getResponseHeadersAsMapOfStringList(response), resultClass);
                } else {
                    logger.logDebug("Response binary");
                    // start hack
                    // https://github.com/microsoftgraph/msgraph-sdk-java/issues/176
                    try{
                        in = checkStreamIsNotEmpty(in);
                    } catch (EmptyInputStreamException ex) {
                        logger.logDebug("Binary response with empty stream");
                        return handleEmptyResponse(getResponseHeadersAsMapOfStringList(response), resultClass);
                    }
                    // finish hack
                    isBinaryStreamInput = true;
                    //no inspection unchecked
                    return (Result) handleBinaryStream(in);
                }`

`private InputStream checkStreamIsNotEmpty(InputStream inputStream) throws IOException, EmptyInputStreamException {
        PushbackInputStream pushbackInputStream = new PushbackInputStream(inputStream);
        int b;
        b = pushbackInputStream.read();
        if ( b == -1 ) {
            throw new EmptyInputStreamException("No byte can be read from stream " + inputStream);
        }
        pushbackInputStream.unread(b);
        return pushbackInputStream;
    }

    private static class EmptyInputStreamException extends RuntimeException {
        public EmptyInputStreamException(String message) {
            super(message);
        }
    }`

**Comment by baywet** [comment] 2020-09-09 15:15
Hi everyone,
Thanks for your feedback and your patience on the matter.
After inspecting #177 and merging the latest changes, it appeared it didn't solve this issue.
I have authored #454 which solves this issue. It will go out with version 2.1.0 of the library (scheduled to go out this week).
This issue will be closed whenever the PR gets merged.

**Closed** 2020-09-09 16:04 UTC
Labels: bug, fixed, tracked
