### ISSUE TITLE
HTTP response code 401 leads to NullPointerException 

### ISSUE THREAD

**Issue by ZuperKeurZ** [microsoftgraph/msgraph-sdk-java#210] opened 2019-01-16 22:33 UTC
expected behaviour: GraphServiceException
actual behaviour: during creation of GraphServiceException a NPE arises
steps to reproduce: provide an invalid, outdated or missing scopes BEARER token

<pre>
java.lang.NullPointerException: source
	at java.util.Objects.requireNonNull(Objects.java:228)
	at java.util.Scanner.<init>(Scanner.java:578)
	at com.microsoft.graph.http.DefaultHttpProvider.streamToString(DefaultHttpProvider.java:440)
	at com.microsoft.graph.http.GraphServiceException.createFromConnection(GraphServiceException.java:314)
	at com.microsoft.graph.http.DefaultHttpProvider.handleErrorResponse(DefaultHttpProvider.java:376)
	at com.microsoft.graph.http.DefaultHttpProvider.sendRequestInternal(DefaultHttpProvider.java:309)
	at com.microsoft.graph.http.DefaultHttpProvider.send(DefaultHttpProvider.java:197)
	at com.microsoft.graph.http.DefaultHttpProvider.send(DefaultHttpProvider.java:177)
	at com.microsoft.graph.http.BaseRequest.send(BaseRequest.java:277)
	at com.microsoft.graph.requests.generated.BaseEventRequest.post(BaseEventRequest.java:116)
	at com.microsoft.graph.requests.generated.BaseEventCollectionRequest.post(BaseEventCollectionReque.st.java:69)
...
</pre>

**Comment by deepak2016** [comment] 2019-01-17 02:43
Thanks for reporting the issue. We are looking into it.

**Comment by deepak2016** [comment] 2019-01-18 09:52
I tried making request with invalid access token and I'm getting GraphServiceException correctly. I'm not able to repro your scenario, can you provide more details on how you are using it?
``
SEVERE: Throwable detail: com.microsoft.graph.http.GraphServiceException: Error code: InvalidAuthenticationToken
Error message: Access token has expired.
``

**Comment by deepak2016** [comment] 2019-01-22 06:04
@ZuperKeurZ  can you provide more info on how you are encountering the error mentioned. In our internal testing, we are not able to reproduce this issue. Thanks

**Comment by deepak2016** [comment] 2019-02-01 10:04
Closing this issue as it is not reproducible. If you are still facing this issue, kindly reopen it.

**Closed by deepak2016** 2019-02-01 10:04 UTC

**Comment by ZuperKeurZ** [comment] 2019-02-01 11:39
Hi Deepak, sorry for the inactivity. 

I had an accident 2 weeks ago and have not been able to continue work.

It's fine to close, if i can reproduce it I will reopen it.

**Comment by lion7** [comment] 2019-05-25 16:02
I'm facing this NullPointerException almost daily... It seems to be caused by an error response that has no body. The connection's `InputStream` is passed down to `com.microsoft.graph.http.DefaultHttpProvider.streamToString(DefaultHttpProvider.java:452)` where the input is read into a `String`. The problem is caused by the fact that the `InputStream` can be null, so a null check should be added there. The original error code of the response is discarded because of this NPE by the way, so I don't know how to exactly reproduce this issue...

**Comment by NakulSabharwal** [comment] 2019-05-28 02:39
@lion7 This issue has been resolved in the latest release. Could you please check if you are still getting error.

**Comment by lion7** [comment] 2019-06-07 19:10
Sorry for the late reply, this issue is indeed fixed in the latest release :smile:
