### ISSUE TITLE
PUT is non-available in buildRequest()  

### ISSUE THREAD

**Issue by dev-andreshv2** [microsoftgraph/msgraph-sdk-java#344] opened 2020-02-28 22:43 UTC
According to the documentation of the Team creation in graph ( 

https://docs.microsoft.com/en-us/graph/api/team-put-teams?view=graph-rest-1.0&tabs=java

), the type of expected HTTP request is a PUT (PUT /groups/{id}/team)

Thus, an example is given at the bottom of the page:
graphClient.groups("{id}").team().buildRequest().put(team);

However, the PUT method does not exist in the interface ITeamRequest.

**Comment by MIchaelMainer** [comment] 2020-03-05 21:23
This may be caused by:
* A required update to the models.
* A generation issue
* May require a custom request builder.

Added to our todo pile

**Comment by userNsu** [comment] 2020-03-06 19:36
@dev-andreshv2 I was also facing the same issue. Did you find any other way to handle it ?

**Comment by Romadelf** [comment] 2020-04-22 14:18
I am facing the issue too.
Note that this issue is a duplicate of https://github.com/microsoftgraph/msgraph-sdk-java/issues/319, where it is currently tagged as a bug and added in the To do of [Graph SDK Generator](https://github.com/orgs/microsoftgraph/projects/9#card-31800403)

**Comment by baywet** [comment] 2020-08-27 20:45
closing as duplicate of #319

**Closed by baywet** 2020-08-27 20:45 UTC
