### ISSUE TITLE
Graph service exception Error code: ErrorQuotaExceeded with message "Cannot get ID from name."

### ISSUE THREAD

**Issue by sunil-marudappa** [microsoftgraph/msgraph-sdk-java#765] opened 2021-05-18 12:53 UTC
Dear Team,

I am creating the draft message using graph-sdk 3.1,0. I am able to get the draftedMessageId.
Using this id, I am trying to update the draft with to, cc, bcc, body, I am trying to call patch request with updated values, I am getting below error which says "Error message: Cannot get ID from name.". I am trying to understand this issue here, kindly help me what is issue here, same error is coming while sending the email after draft creation(with to, cc).

2021-05-17 12:45:23.460 ERROR 43840 --- [ctor-http-nio-3] global : Throwable detail: com.microsoft.graph.http.GraphServiceException: Error code: ErrorQuotaExceeded
Error message: Cannot get ID from name.

PATCH https://graph.microsoft.com/v1.0/users/XXXXXXX/messages/AAMkADIzOTk0ZGE0LTM3NDMtNDVmNC1hMDI1LWNhZjhlYTY4NzYyZABGAAAAAADNi3vV7r2rQZhnzEtDpBVbBwBuk9kw84y_Q5iZ3kzrhAWXAAAAAAEPAABuk9kw84y_Q5iZ3kzrhAWXAAAmMbyVAAA=
SdkVersion : graph-java/v3.1.0
[...]

403 : Forbidden
[...]

SingleValueLegacyExtendedPropertyCollectionResponse response = new SingleValueLegacyExtendedPropertyCollectionResponse();
		SingleValueLegacyExtendedProperty property = new SingleValueLegacyExtendedProperty();
		property.id = "String " + UUID.randomUUID().toString() + " Name " + "UpdateEmailUUID";
		property.value = SINGLE_EXTENDED_PROPERTY_VALUE;
		response.value = Arrays.asList(property); 
		SingleValueLegacyExtendedPropertyCollectionRequestBuilder builder 
				= new SingleValueLegacyExtendedPropertyCollectionRequestBuilder("", graphClient, null);
		SingleValueLegacyExtendedPropertyCollectionPage collectionPage = new SingleValueLegacyExtendedPropertyCollectionPage(response, builder);
		message.singleValueExtendedProperties = collectionPage;

I am trying to understand the meaning of error message, what is causing this issue ? what is the fix for this ?
Kindly help me in this, there is not much documentation available on this issue. 
[AB#9498](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/9498)

**Comment by baywet** [comment] 2021-05-18 13:30
closing as duplicate of #764

**Closed by baywet** 2021-05-18 13:30 UTC
Labels: ToTriage
