### ISSUE TITLE
Caused by: java.lang.ClassCastException: java.io.BufferedInputStream cannot be cast to com.google.gson.JsonElement

### ISSUE THREAD

**Issue by shbaotou** [microsoftgraph/msgraph-sdk-java#1762] opened 2024-02-01 04:25 UTC
![Exception of Cannot be cast ](https://github.com/microsoftgraph/msgraph-sdk-java/assets/59996177/200eb12c-9bad-473d-9b68-a586ffd8aac3)

Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:109)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88)
Caused by: java.lang.ClassCastException: java.io.BufferedInputStream cannot be cast to com.google.gson.JsonElement
	at com.aia.fas.batch.controller.UploadFileController.uploadSession(UploadFileController.java:49)
	at com.aia.fas.batch.service.impl.UploadFileServiceImpl.uploadFile(UploadFileServiceImpl.java:33)
	at com.aia.fas.batch.adapter.BatchJobForwardHandler.handleApiForward(BatchJobForwardHandler.java:27)
	at com.aia.fas.batch.SharePointApplication.main(SharePointApplication.java:35)
	... 8 more

We are receiving this kind of error while using the graph API to upload file to SharePoint. 
But we have no idea why it happen as we are not doing anything change and the program running well before yesterday.

**Comment by shbaotou** [comment] 2024-02-01 08:02
The error occurs at this position.
![Exception of Cannot be cast2 ](https://github.com/microsoftgraph/msgraph-sdk-java/assets/59996177/51e69f42-1ff0-4748-9105-f772c7e3c1ec)

**Comment by baywet** [comment] 2024-02-01 10:36
Closing as duplicate of #1761

**Closed** 2024-02-01 10:36 UTC

**Comment by shbaotou** [comment] 2024-02-02 01:59
@baywet ,
May I know why it happen suddenly?

**Comment by baywet** [comment] 2024-02-02 11:32
See this reply https://github.com/microsoftgraph/msgraph-sdk-java/issues/1761#issuecomment-1919919802

**Comment by shbaotou** [comment] 2024-02-02 12:23
@baywet ,
Thanks your reply,
I have upgrade the Microsoft Graph Java SDK to 2.2.0 from 1.7 and the problem fixed yesterday.
I have saw the #1761, but the error message not exactly same with mine.
Is the error type of #1761 same with mine?
Just want to know more detail of why this error is happen suddenly?
because our program run normally previous until Jan 31 2024.

Kindly need your advise.
Thanks.
