### ISSUE TITLE
Support retry policies, e.g. exponential backoff

### ISSUE THREAD

**Issue by Kitanotori** [microsoftgraph/msgraph-sdk-java#133] opened 2018-09-12 10:13 UTC
### Expected behavior

Should be possible to set retry policy, such as exponential backoff, in similar way to [google-http-java-client](https://developers.google.com/api-client-library/java/google-http-java-client/backoff)

See https://github.com/googleapis/google-http-java-client for reference implementation.

### Actual behavior

No obvious way to set retry policy.

**Comment by deepak2016** [comment] 2018-09-12 13:16
@Kitanotori Thanks for reporting the issue. This helps us to prioritize the features to work on next.
We have this in our backlog and we will be taking up this item soon.

**Comment by J0s3f** [comment] 2018-09-20 11:57
This looks like a duplicate of #91

**Comment by darrelmiller** [comment] 2018-09-20 14:04
@Kitanotori We are gathering requirements for retry behavior in a design document here https://github.com/microsoftgraph/msgraph-sdk-design/blob/master/middleware/RetryHandler.md  We welcome your input as to whether what we have outlined will meet your requirements.

**Comment by Kitanotori** [comment] 2018-10-11 02:14
@darrelmiller submitted proposal regarding exponential backoff https://github.com/microsoftgraph/msgraph-sdk-design/pull/3

**Comment by NakulSabharwal** [comment] 2019-07-11 01:49
Hi @Kitanotori ,we have integrated out [msgraph-sdk-core](https://github.com/microsoftgraph/msgraph-sdk-java-core) with this sdk and now supporting retry with exponential backoff. Thanks.

**Closed by NakulSabharwal** 2019-07-11 01:49 UTC

**Comment by Kitanotori** [comment] 2019-07-12 06:07
@NakulSabharwal How do I use exponential backoff with GraphServiceClient?

**Comment by heyalistair** [comment] 2019-09-24 09:42
@Kitanotori I'm not an export in the implementation of this SDK, but it looks like from src/main/java/com/microsoft/graph/http/BaseRequest.java that it retries with exponential backoff by default.
