### ISSUE TITLE
Unable to get 'createdDateTime' parameter in Recent Files API 

### ISSUE THREAD

**Issue by tusharaina92** [microsoftgraph/msgraph-sdk-java#798] opened 2021-06-11 18:40 UTC
### Expected behavior
`IDriveRecentCollectionRequestBuilder.buildRequest().top(30).get();` should return `DriveItem` with parameters at par with `IDriveItemCollectionRequestBuilder.buildRequest().get()`.

### Actual behavior
`IDriveRecentCollectionRequestBuilder.buildRequest().top(30).get();` is returning `DriveItem` with `createdDateTime` as `null` for some of the files. The files for which I have tested are not shared files. While `IDriveItemCollectionRequestBuilder.buildRequest().get()` is returning the `DriveItem` with `createdDateTime` as non-null for these same files.

### Steps to reproduce the behavior
Its always happening even for 'https://graph.microsoft.com/v1.0/me/drive/recent' in API explorer.
For my Android Application, these are the following details:
ms_graph_version = '2.10.0'
android_gradle_plugin = '4.0.2'
Android Studio version = '4.1.1'
 
[AB#9878](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/9878)

**Comment by baywet** [comment] 2021-06-11 19:06
Hi @tusharaina92 
Thanks for reaching out.
Can you try upgrading to the latest version of this library (3.8.0 at the moment of writing) and see if you still run into the issue please?

**Comment by tusharaina92** [comment] 2021-06-11 20:40
@baywet I tried with sample app upgrading graph version but still returning null value for this parameter. Is there any particular change that has been made in this SDK to address this issue or do I need to configure something extra apart from just updating the  graph version?

**Comment by baywet** [comment] 2021-06-14 13:15
@tusharaina92 it's difficult to answer this specific question, we've fixed dozens of bugs between those two versions.
However I can confirm that the following unit test passes on my dev tenant"
```Java
final DriveRecentCollectionPage result = testBase.graphClient.me()
			.drive()
			.recent()
            .buildRequest()
            .top(2)
            .get();
        assertNotNull(result.getCurrentPage().get(0).createdDateTime);
        assertEquals(4, result.getCurrentPage().get(0).createdDateTime.getDayOfMonth());
```

**Comment by tusharaina92** [comment] 2021-06-14 18:22
@baywet I ran the query on the API explorer and below are the result for some of my file using query ::
`https://graph.microsoft.com/v1.0/me/drive/recent`

```json
{
            "@odata.type": "#microsoft.graph.driveItem",
            "id": "0152JPEDQ367YG7ZBADFGYJQXA4FSQZMON",
            "lastModifiedDateTime": "2020-01-27T07:19:05Z",
            "name": "Download.zip",
            "size": 2674204,
            "lastModifiedBy": {
                "user": {
                    "displayName": "Alex Martin",
                    "email": "alex19@example.com"
                }
            },
            "parentReference": {
                "driveId": "b!I1zxuv8jFnBtkKbHuifArMU95hmyHU1yPZGvEGSWB0iusvpz1h3lPInS4EK63Vpc4i5",
                "driveType": "business"
            },
            "file": {
                "mimeType": "application/zip"
            },
            "fileSystemInfo": {
                "lastModifiedDateTime": "2020-01-27T07:19:05Z",
                "lastAccessedDateTime": "2020-01-27T07:19:03Z"
            },
            "remoteItem": {
                "id": "0152JPEDQ123367YG7ZBADFGYJQXA4FSQZMON",
                "lastModifiedDateTime": "2020-01-27T07:19:05Z",
                "name": "Download.zip",
                "size": 2674204,
                "webDavUrl": "https://example-my.sharepoint.com/personal/example/Documents/MAC_DownloadFolder_BackUp/Download.zip",
                "file": {
                    "mimeType": "application/zip"
                },
                "fileSystemInfo": {
                    "lastModifiedDateTime": "2020-01-27T07:19:05Z",
                    "lastAccessedDateTime": "2020-01-27T07:19:03Z"
                },
                "lastModifiedBy": {
                    "user": {
                        "displayName": "Alex Martin",
                        "email": "alex19@example.com"
                    }
                },
                "parentReference": {
                    "driveId": "b!Iuv8aasjFnBtkKbHuifArMU95hmyHU1yPZGvEGSWB0iusvpz1h3lPInS4EK63Vpc4i5",
                    "driveType": "business"
                },
                "sharepointIds": {
                    "listId": "775812cfe9-f294-4b27-810a-eb75697388b9",
                    "listItemId": "0",
                    "listItemUniqueId": "6ff0f171b-20e4-4d19-84c2-e0e1650cb1cd",
                    "siteId": "8cfceb22-c2159-42b6-9b1e-e89f02b314f7",
                    "webId": "75c863698-c835-46f6-bc41-92581d22bacb"
                }
            }
        }
```
In the above API response I could see createdDateTime field is missing which is converting to `null` in the SDK and causing the issue. In the file listing API/getDrive item, createdDateTime is coming as expected.

**Comment by baywet** [comment] 2021-06-14 18:26
@tusharaina92 this is interesting, I do get the createdDateTime information on the recent endpoint on my dev tenant.
At this point this looks like a service issue specific to your tenant and you should engage with the [service support](https://developer.microsoft.com/en-us/graph/support).
Closing.

**Closed by baywet** 2021-06-14 18:26 UTC
Labels: Needs: Attention :wave:, question

**Comment by tusharaina92** [comment] 2021-06-14 19:25
@baywet Is there any other Github repo wherein I can have more info for this service related issue?

**Comment by baywet** [comment] 2021-06-14 19:32
you can try to search in [the docs repo](https://github.com/microsoftgraph/microsoft-graph-docs/issues). If you want to open a new issue there, don't create it from GitHub, instead go on the "recent" documentation page, and at the bottom, use the feedback section.
