### ISSUE TITLE
Java enum template needs to include SerializableName for each member

### ISSUE THREAD

**Issue by MIchaelMainer** [microsoftgraph/msgraph-sdk-java#587] opened 2020-11-17 00:18 UTC
https://github.com/microsoftgraph/MSGraph-SDK-Code-Generator/blob/dev/Templates/Java/models_generated/Enum.java.tt

```java
public void testGetMailtips() {
		TestBase testBase = new TestBase();
		ArrayList<String> users = new ArrayList<String>();
		users.add("michael@chambele.onmicrosoft.com");
		users.add("AdeleV@chambele.onmicrosoft.com");
		EnumSet<MailTipsType> mailtips = EnumSet.of(MailTipsType.MAILBOX_FULL_STATUS, MailTipsType.MAX_MESSAGE_SIZE);
		UserGetMailTipsCollectionPage page = testBase.graphClient.me().getMailTips(users, mailtips).buildRequest().post();
		assertNotNull(page);
	}
```
results in the following body:
```json
{
    "emailAddresses": ["michael@chambele.onmicrosoft.com", "AdeleV@chambele.onmicrosoft.com"],
    "mailTipsOptions": "MAILBOX_FULL_STATUS,MAX_MESSAGE_SIZE"
}
```
expected:
```json
{
    "emailAddresses": ["michael@chambele.onmicrosoft.com", "AdeleV@chambele.onmicrosoft.com"],
    "mailTipsOptions": "mailboxFullStatus,maxMessageSize"
}
```

**Comment by baywet** [comment] 2020-12-04 18:49
@MIchaelMainer this was actually not caused by a lack of annotations by rather by the fact that our fallback adapter was not being used in one of the serialization/deserialization paths. I transferred the issue to the service library repo and authored #588 to fix it. Thanks for reporting it!

**Closed** 2020-12-07 16:28 UTC
Labels: bug, fixed
