### ISSUE TITLE
Not a JSON Object error on the last call of ChunkedUploadProvider.upload (large file)

### ISSUE THREAD

**Issue by mmerlet** [microsoftgraph/msgraph-sdk-java#171] opened 2018-12-06 15:34 UTC
Tested version 1.0.1
Trying to upload large file (8 Mo) : the last call generate an exception. 
However, the file is correctly created one the onedrive plateform.

### Expected behavior
The response should be correctly deserialized to DriveItem

### Actual behavior
The first x calls are correcly executed but the last throws an exception :

GRAVE: DefaultHttpProvider[send] - 197Error during http request
déc. 06, 2018 4:34:41 PM com.microsoft.graph.logger.DefaultLogger logError
GRAVE: Throwable detail: com.microsoft.graph.core.ClientException: Error during http request
com.microsoft.graph.core.ClientException: Request failed with error, retry if necessary.
	at com.microsoft.graph.requests.extensions.ChunkedUploadRequest.upload(ChunkedUploadRequest.java:115)
	at com.microsoft.graph.concurrency.ChunkedUploadProvider.upload(ChunkedUploadProvider.java:180)
	at com.microsoft.graph.concurrency.ChunkedUploadProvider.upload(ChunkedUploadProvider.java:208)
	at fr.vif.office.DemoOffice$4.success(DemoOffice.java:252)
	at fr.vif.office.DemoOffice$4.success(DemoOffice.java:1)
	at com.microsoft.graph.concurrency.DefaultExecutors$1.run(DefaultExecutors.java:92)
	at com.microsoft.graph.concurrency.SynchronousExecutor.execute(SynchronousExecutor.java:45)
	at com.microsoft.graph.concurrency.DefaultExecutors.performOnForeground(DefaultExecutors.java:89)
	at com.microsoft.graph.http.DefaultHttpProvider$1.run(DefaultHttpProvider.java:148)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.microsoft.graph.core.ClientException: Error during http request
	at com.microsoft.graph.http.DefaultHttpProvider.sendRequestInternal(DefaultHttpProvider.java:356)
	at com.microsoft.graph.http.DefaultHttpProvider.send(DefaultHttpProvider.java:197)
	at com.microsoft.graph.requests.extensions.ChunkedUploadRequest.upload(ChunkedUploadRequest.java:113)
	... 11 more
Caused by: java.lang.IllegalStateException: Not a JSON Object: [{"id":"0","large":{"height":800,"url":"https://1gqorw.dm.files.1drv.com/y4pvdt5TrMHJaat4aUkkHggToN6ImvRbvFv0-fc3rbOImLUdARxPEFLwlmvX9_YuyAt5pLT8KHdpBsosP9C6lzdPQKsru3Je3lLqh8QhMWHZHBFvdIBLIwp6oF582GXnQuM-FDgH9dYAY3IBVXd2vmbtex1L5mE2MoKFST_bnMaJ7iJPf_HVNznk0RkB28LNoCqGqIZ6oey2_HwqXZKXdjrlCUIk9rKdwHO_pzQtPuStuA?width=800&height=800&cropmode=none","width":800},"medium":{"height":176,"url":"https://1gqorw.dm.files.1drv.com/y4pvdt5TrMHJaat4aUkkHggToN6ImvRbvFv0-fc3rbOImLUdARxPEFLwlmvX9_YuyAt5pLT8KHdpBsosP9C6lzdPQKsru3Je3lLqh8QhMWHZHBFvdIBLIwp6oF582GXnQuM-FDgH9dYAY3IBVXd2vmbtex1L5mE2MoKFST_bnMaJ7iJPf_HVNznk0RkB28LNoCqGqIZ6oey2_HwqXZKXdjrlCUIk9rKdwHO_pzQtPuStuA?width=176&height=176&cropmode=none","width":176},"small":{"height":96,"url":"https://1gqorw.dm.files.1drv.com/y4pvdt5TrMHJaat4aUkkHggToN6ImvRbvFv0-fc3rbOImLUdARxPEFLwlmvX9_YuyAt5pLT8KHdpBsosP9C6lzdPQKsru3Je3lLqh8QhMWHZHBFvdIBLIwp6oF582GXnQuM-FDgH9dYAY3IBVXd2vmbtex1L5mE2MoKFST_bnMaJ7iJPf_HVNznk0RkB28LNoCqGqIZ6oey2_HwqXZKXdjrlCUIk9rKdwHO_pzQtPuStuA?width=96&height=96&cropmode=none","width":96}}]
	at com.google.gson.JsonElement.getAsJsonObject(JsonElement.java:91)
	at com.microsoft.graph.serializer.DefaultSerializer.setChildAdditionalData(DefaultSerializer.java:147)
	at com.microsoft.graph.serializer.DefaultSerializer.deserializeObject(DefaultSerializer.java:103)
	at com.microsoft.graph.serializer.DefaultSerializer.deserializeObject(DefaultSerializer.java:72)
	at com.microsoft.graph.concurrency.ChunkedUploadResponseHandler.generateResult(ChunkedUploadResponseHandler.java:102)
	at com.microsoft.graph.concurrency.ChunkedUploadResponseHandler.generateResult(ChunkedUploadResponseHandler.java:44)
	at com.microsoft.graph.http.DefaultHttpProvider.sendRequestInternal(DefaultHttpProvider.java:302)
	... 13 more

### Steps to reproduce the behavior
      File f = new File("C:\\Users\\mm\\tests\\office\\bigFile.pdf"); // file bigger than 5 Mo

       DriveItemUploadableProperties item = new DriveItemUploadableProperties();
        graphClient.me().drive().root().itemWithPath(f.getName()).createUploadSession(item).buildRequest()
        .post(new ICallback<UploadSession>() {
            @Override
            public void failure(final ClientException ex) {
                ex.printStackTrace();
            }

            @Override
            public void success(final UploadSession result) {
                System.out.println("OK createUploadSession : " + result);
                try {

                            FileInputStream fis = new FileInputStream(f);
                            ChunkedUploadProvider<DriveItem> cup = new ChunkedUploadProvider<DriveItem>(result, graphClient, fis, (int) f.length(), DriveItem.class);

                            cup.upload(new IProgressCallback<DriveItem>() {
                                @Override
                                public void failure(final ClientException ex) {
                                    ex.printStackTrace();
                                }

                                @Override
                                public void progress(final long current, final long max) {
                                    System.out.println("\tProgress : " + current + " (max=" + max + ")");
                                }

                                @Override
                                public void success(final DriveItem result) {
                                    System.out.println("End OK");
                                }
                            }, new int[] { 10 * 320 * 1024 });

                        } catch (Exception e) {
                             e.printStackTrace();
                      }
            }
        });

**Comment by NakulSabharwal** [comment] 2018-12-06 15:51
Thank you for reporting your issue. We are looking into it.

**Comment by NakulSabharwal** [comment] 2019-01-06 10:40
Hi, I was not able to repro your issue using the code snippet provided by uploading a file of 10mb and it is working perfectly fine. You can get the url by editing this function - 

	public void success(final DriveItem result) {
			System.out.println(result.webUrl); // here is the webUrl of item uploaded by you
			System.out.println("End OK");
	}

**Comment by NakulSabharwal** [comment] 2019-01-07 07:05
The error is being caused by
```
Not a JSON Object
...
at com.google.gson.JsonElement.getAsJsonObject(JsonElement.java:91)
at com.microsoft.graph.serializer.DefaultSerializer.setChildAdditionalData(DefaultSerializer.java:147)
```

which is because since the given json is not JsonObject but instead a JsonArray so it throws this error, in the latest msgraph-sdk-java repository code this issue has been fixed by adding null check in DefaultSerializer.java line:147.
`if(rawJson != null && field != null && rawJson.get(field.getName()) != null && rawJson.get(field.getName()).isJsonObject()) {`
The jar with the required fix is going to be released very soon.

**Comment by NakulSabharwal** [comment] 2019-01-09 06:59
Hi, if you still face problem please reopen this issue. Thank you.

**Closed** 2019-01-09 06:59 UTC
