### ISSUE TITLE
Error while reading mails: java.io.BufferedInputStream cannot be cast to com.microsoft.graph.requests.extensions.MailFolderCollectionResponse(loaded by com.sap.engine.boot.loader.ResourceMultiParentClassLoader@0x00000007f02e3510)

### ISSUE THREAD

**Issue by madelgalman** [microsoftgraph/msgraph-sdk-java#1761] opened 2024-01-31 19:38 UTC
<img width="917" alt="image" src="https://github.com/microsoftgraph/msgraph-sdk-java/assets/158341999/ca3d1fbd-04c3-4fcc-9a54-c1058389029d">

We are receiving this kind of error. But we have no idea where it came from as we are not doing anything.
It is properly working then it just happen one time up to now.

**Comment by kenguil** [comment] 2024-01-31 20:26
FYI: This is occurring for multiple users across multiple companies. Beyond MailFolderCollectionResponse, we're also seeing this with MailMessageCollectionResponse.

**Comment by baywet** [comment] 2024-01-31 20:28
From the support team (Antonio San Pedro) customers reporting this issue are running Microsoft Graph Java SDK 1.7
The current version of the SDK is 5.X and we're working to GA 6 in the semester.
Anything <5 is not supported and hasn't been for a long time. The recommendation is to upgrade the SDK version in the application, to 5.X if possible, or at least 2.1 from the note above.

**Comment by baywet** [comment] 2024-01-31 20:40
After further investigations this seems to be caused by the fact the service is replying with HTTP/2 (deployment in progress, expected).
[Here is the initial announcement for that change](https://techcommunity.microsoft.com/t5/microsoft-entra-blog/microsoft-entra-change-announcements-september-2022-train/ba-p/2967454)
The recommendation is for customers to upgrade their outdated dependencies as soon as possible.

**Comment by baywet** [comment] 2024-02-08 13:57
Closing since there's no action to take on this one besides customers updating their dependencies or disabling http/2 on the client.

**Closed by baywet** 2024-02-08 13:57 UTC
Labels: question, Needs: Attention :wave:
