### ISSUE TITLE
[BUG] Application never end when trying to connect to sharepoint via client secret credentials 

### ISSUE THREAD

**Issue by ihudedi** [microsoftgraph/msgraph-sdk-java#2210] opened 2024-10-29 10:30 UTC
Hi,
I am trying to connect to Sharepoint via graph api and trying to connect to SPO with client secret credentials
and application hung with same message as
2024-10-28 18:46:05,578 DEBUG [qtp236567414-16] (ClientSecretCredential:564) - Azure Identity => getToken() result for scopes [https://graph.microsoft.com/.default]: SUCCESS
Getting this line in a loop
and system never finished.
What can cause this line in loop over and over
Thanks,
Itay

**Comment by ihudedi** [comment] 2024-11-05 18:42
Hi @baywet 
Are you familiar with this issue?
Thanks,
Itay

**Comment by ihudedi** [comment] 2024-11-06 07:46
This is the lines from the logs when trying to list sites
2024-10-28 18:46:07,589 DEBUG [ForkJoinPool.commonPool-worker-3] (AcquireTokenSilentSupplier:58) - Returning token from cache
2024-10-28 18:46:07,589 DEBUG [ForkJoinPool.commonPool-worker-3] (ConfidentialClientApplication:141) - [Correlation ID: 5e821149-90cc-4cc6-861d-2a660a3c82c0] Access Token was returned
2024-10-28 18:46:07,589 DEBUG [qtp236567414-16] (ClientSecretCredential:564) - Azure Identity => getToken() result for scopes [https://graph.microsoft.com/.default]: SUCCESS
2024-10-28 18:46:08,119 DEBUG [ForkJoinPool.commonPool-worker-3] (AcquireTokenSilentSupplier:58) - Returning token from cache
2024-10-28 18:46:08,120 DEBUG [ForkJoinPool.commonPool-worker-3] (ConfidentialClientApplication:141) - [Correlation ID: b21c78a6-ecc3-47f6-859a-3dd3bb0d7210] Access Token was returned
2024-10-28 18:46:08,120 DEBUG [qtp236567414-16] (ClientSecretCredential:564) - Azure Identity => getToken() result for scopes [https://graph.microsoft.com/.default]: SUCCESS
2024-10-28 18:46:08,749 DEBUG [ForkJoinPool.commonPool-worker-3] (AcquireTokenSilentSupplier:58) - Returning token from cache
2024-10-28 18:46:08,750 DEBUG [ForkJoinPool.commonPool-worker-3] (ConfidentialClientApplication:141) - [Correlation ID: c55647cd-e106-4898-87f4-c7d3189d83e6] Access Token was returned
2024-10-28 18:46:08,750 DEBUG [qtp236567414-16] (ClientSecretCredential:564) - Azure Identity => getToken() result for scopes [https://graph.microsoft.com/.default]: SUCCESS
2024-10-28 18:46:09,848 DEBUG [ForkJoinPool.commonPool-worker-3] (AcquireTokenSilentSupplier:58) - Returning token from cache
2024-10-28 18:46:09,848 DEBUG [ForkJoinPool.commonPool-worker-3] (ConfidentialClientApplication:141) - [Correlation ID: 79dc9305-a579-49e9-b85e-f8702cdae43c] Access Token was returned
2024-10-28 18:46:09,848 DEBUG [qtp236567414-16] (ClientSecretCredential:564) - Azure Identity => getToken() result for scopes [https://graph.microsoft.com/.default]: SUCCESS
2024-10-28 18:46:10,376 DEBUG [ForkJoinPool.commonPool-worker-3] (AcquireTokenSilentSupplier:58) - Returning token from cache
2024-10-28 18:46:10,377 DEBUG [ForkJoinPool.commonPool-worker-3] (ConfidentialClientApplication:141) - [Correlation ID: 236b3971-154e-4297-8588-eae56cf56c12] Access Token was returned
2024-10-28 18:46:10,377 DEBUG [qtp236567414-16] (ClientSecretCredential:564) - Azure Identity => getToken() result for scopes [https://graph.microsoft.com/.default]: SUCCESS
2024-10-28 18:46:10,926 DEBUG [ForkJoinPool.commonPool-worker-3] (AcquireTokenSilentSupplier:58) - Returning token from cache
2024-10-28 18:46:10,927 DEBUG [ForkJoinPool.commonPool-worker-3] (ConfidentialClientApplication:141) - [Correlation ID: 9a48bb24-d85a-4fe7-a1a1-d4bab5063471] Access Token was returned
2024-10-28 18:46:10,927 DEBUG [qtp236567414-16] (ClientSecretCredential:564) - Azure Identity => getToken() result for scopes [https://graph.microsoft.com/.default]: SUCCESS
2024-10-28 18:46:11,406 DEBUG [ForkJoinPool.commonPool-worker-3] (AcquireTokenSilentSupplier:58) - Returning token from cache

And it doesn't stop in a loop

**Comment by Ndiritu** [comment] 2024-11-07 13:30
Hi @ihudedi.
Thank you for reaching out.
Will try to reproduce this and share the outcomes. Does this only happen when calling SharePoint endpoints?

**Comment by Ndiritu** [comment] 2024-11-07 13:32
Could you please share what version of the SDK you're using, version of Azure Identity lib you're using & some platform specs: Java version etc?

**Comment by baywet** [comment] 2024-11-10 05:26
If you're using a client secret, try with a certificate instead. From memory a number of operations on the SharePoint APIs require certificates for security reasons.
Azure Identity should fail with an error message though instead of looping. As you can see, the whole stack you've shared comes from Azure Identity, I'd suggest that you create a minimal reproduction repository and share it in an issue [here](https://github.com/azure/azure-sdk-for-java) so the right people can look at it.

**Comment by ihudedi** [comment] 2024-11-14 07:53
Hi @baywet 
thanks for the response.
I already sent an issue to the azure team.
Thanks,
Itay

**Comment by baywet** [comment] 2024-11-14 13:26
Thank you for the additional information.
Closing since there's no action to take in the SDK itself.

**Closed by baywet** 2024-11-14 13:26 UTC
Labels: Needs: Attention :wave:, type:question
