### ISSUE TITLE
$expand=permissions on items throws a json parsing error on the sdk 

### ISSUE THREAD

**Issue by mmarmol** [microsoftgraph/msgraph-sdk-java#495] opened 2020-09-23 16:10 UTC
### Expected behavior

Should return an item with values in the permissions field.

### Actual behavior

There is a ClientException when trying to ask for the option of $expand=permissions on an item:
Expected BEGIN_OBJECT but was BEGIN_ARRAY at line 1 column 1331 path $.permissions

### Steps to reproduce the behavior

Create an init a client:
private final IGraphServiceClient client; //DO THE CORRECT INIT AND ASIGN THE VALUE
client.me().drive().items("YOUR_ID_HERE").buildRequest(Arrays.asList(new QueryOption("$expand", "permissions"))).get());

The exception will be throw.

**Comment by baywet** [comment] 2020-09-23 16:40
Hi, thanks for reaching out.
Most likely a duplicate of #475.
Can you tell us what version of the SDK you are using? Were you using another version previously (upgrade) and if yes was it working and what version was it?
Can you provide a longer stack track as well please?

**Comment by mmarmol** [comment] 2020-09-23 16:51
version 2.1.0, we were not using the previous version.

Here is the URL that was requested by the SDK ($$$$$$$$$$ used for conceal data):
**https://graph.microsoft.com/v1.0/me/drive/items/$$$$$$$$$$?%24expand=permissions**

Here is the api JSON raw reply ($$$$$$$$$$ used for conceal data):
```
{
	"@odata.context": "https://graph.microsoft.com/v1.0/$metadata#users('$$$$$$$$$$')/drive/items(permissions())/$entity",
	"createdDateTime": "2020-09-22T21:04:06Z",
	"eTag": "\"{$$$$$$$$$$},1\"",
	"id": "$$$$$$$$$$",
	"lastModifiedDateTime": "2020-09-22T21:04:06Z",
	"name": "get_folder",
	"webUrl": "https://mxheroinc-my.sharepoint.com/personal/mmarmol_corp_mxhero_com/Documents/unit_testing_sdk/get_folder",
	"cTag": "\"c:{$$$$$$$$$$},0\"",
	"size": 0,
	"createdBy": {
		"user": {
			"email": "$$$$$$$$$$",
			"id": "$$$$$$$$$$",
			"displayName": "$$$$$$$$$$"
		}
	},
	"lastModifiedBy": {
		"user": {
			"email": "$$$$$$$$$$",
			"id": "$$$$$$$$$$",
			"displayName": "$$$$$$$$$$"
		}
	},
	"parentReference": {
		"driveId": "$$$$$$$$$$db8i8",
		"driveType": "business",
		"id": "$$$$$$$$$$",
		"path": "/drive/root:/unit_testing_sdk"
	},
	"fileSystemInfo": {
		"createdDateTime": "2020-09-22T21:04:06Z",
		"lastModifiedDateTime": "2020-09-22T21:04:06Z"
	},
	"folder": {
		"childCount": 0
	},
	"permissions@odata.context": "https://graph.microsoft.com/v1.0/$metadata#users($$$$$$$$$$')/drive/items('$$$$$$$$$$')/permissions",
	"permissions": [{
		"id": "$$$$$$$$$$",
		"roles": ["owner"],
		"grantedTo": {
			"user": {
				"email": "$$$$$$$$$$",
				"id": "$$$$$$$$$$",
				"displayName": "$$$$$$$$$$"
			}
		},
		"inheritedFrom": {}
	}]
}
```
Here stack trace:
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was BEGIN_ARRAY at line 1 column 1331 path $.permissions
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:226)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
	at com.google.gson.Gson.fromJson(Gson.java:932)
	at com.google.gson.Gson.fromJson(Gson.java:897)
	at com.google.gson.Gson.fromJson(Gson.java:846)
	at com.google.gson.Gson.fromJson(Gson.java:817)
	at com.microsoft.graph.serializer.DefaultSerializer.deserializeObject(DefaultSerializer.java:82)
	at com.microsoft.graph.http.CoreHttpProvider.handleJsonResponse(CoreHttpProvider.java:521)
	at com.microsoft.graph.http.CoreHttpProvider.sendRequestInternal(CoreHttpProvider.java:397)
	at com.microsoft.graph.http.CoreHttpProvider.send(CoreHttpProvider.java:204)
	at com.microsoft.graph.http.CoreHttpProvider.send(CoreHttpProvider.java:184)
	at com.microsoft.graph.http.BaseRequest.send(BaseRequest.java:305)
	at com.microsoft.graph.requests.extensions.DriveItemRequest.get(DriveItemRequest.java:84)
	at com.mxhero.storage.onedrive.actions.OneDriveGetFolder.apply(OneDriveGetFolder.java:27)
	at com.mxhero.storage.onedrive.actions.OneDriveGetFolder.apply(OneDriveGetFolder.java:1)
	at com.mxhero.storage.actions.Action.call(Action.java:22)
	at com.mxhero.storage.actions.GetFolder.lambda$byId$1(GetFolder.java:24)
	at com.mxhero.storage.actions.GetFolder$$Lambda$177/0000000000000000.apply(Unknown Source)
	at com.mxhero.storage.onedrive.actions.OneDriveGetFolderTest.test_get_non_root(OneDriveGetFolderTest.java:18)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:89)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:41)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:542)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:770)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:464)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)
Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was BEGIN_ARRAY at line 1 column 1331 path $.permissions
	at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:386)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:215)
	... 42 more

**Comment by baywet** [comment] 2020-09-23 16:56
thanks for the additional details. The stack traces are very similar beside the fact that the owner of the other issue is probably using an older version. I'm going to close this issue for clarity, please follow along on the other one.

**Comment by mmarmol** [comment] 2020-09-23 16:57
Wait, just tested it on 2.2.0 and is working fine. Looks like is something was fixes on 2.2.0 (This Monday release =P). So you can discard this issue.

**Closed by baywet** 2020-09-23 16:56 UTC
Labels: Needs: Attention :wave:, duplicate

**Comment by baywet** [comment] 2020-09-23 17:10
interesting, I'm still seeing similar issues with 2.2.0 in some cases. But it's good to know you're not being impacted. Thanks!

**Comment by mmarmol** [comment] 2020-09-23 17:20
This is the same in both versions 2.1.0 and 2.2.0:    
 @SerializedName("permissions")
    @Expose
    public PermissionCollectionPage permissions;

So my best guess is that PermissionCollectionPage is not corretly set to be parsed as it should by the ObjectMapper, since is complaning to receive an object instead of an array and the response clearly returns an array for that field:

com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: **Expected BEGIN_OBJECT but was BEGIN_ARRAY** at line 1 column 1331 path **$.permissions**

```
"permissions": [{
		"id": "$$$$$$$$$$",
		"roles": ["owner"],
		"grantedTo": {
			"user": {
				"email": "$$$$$$$$$$",
				"id": "$$$$$$$$$$",
				"displayName": "$$$$$$$$$$"
			}
		},
		"inheritedFrom": {}
	}]
```

**Comment by baywet** [comment] 2020-09-23 17:54
so to be clear, you are still having the issue with 2.2.0?

**Comment by mmarmol** [comment] 2020-09-23 17:58
No, 2.2.0 looks fine. Regards
