### ISSUE TITLE
Getting crash in Android OS 7

### ISSUE THREAD

**Issue by atulgpt** [microsoftgraph/msgraph-sdk-java#542] opened 2020-10-15 07:53 UTC
While in process of uploading file to OneDrive, we are getting crash on device OS 7. **We couldn't verify this crash on Android OS level below 7 as we get the crash in CalenderSerializer before this flow kicks in.**

Crash logs are as follow:
--------- beginning of crash 10-15 10:32:12.228 13689 13689 E AndroidRuntime: FATAL EXCEPTION: main 10-15 10:32:12.228 13689 13689 E AndroidRuntime: Process: com.adobe.reader, PID: 13689 10-15 10:32:12.228 13689 13689 E AndroidRuntime: java.lang.NoSuchMethodError: No interface method getTypeName()Ljava/lang/String; in class Ljava/lang/reflect/Type; or its super classes (declaration of 'java.lang.reflect.Type' appears in /system/framework/core-oj.jar) 10-15 10:32:12.228 13689 13689 E AndroidRuntime: at com.microsoft.graph.serializer.CollectionPageSerializer.deserialize(CollectionPageSerializer.java:115) 10-15 10:32:12.228 13689 13689 E AndroidRuntime: at com.microsoft.graph.serializer.GsonFactory$12.deserialize(GsonFactory.java:229) 10-15 10:32:12.228 13689 13689 E AndroidRuntime: at com.microsoft.graph.serializer.GsonFactory$12.deserialize(GsonFactory.java:224) 10-15 10:32:12.228 13689 13689 E AndroidRuntime: at 

### Expected behavior
It shouldn't crash and handle newer apis with fallback mechanish or apis that is supported in older OS version

### Devices tested where issue is observed:
Asus Tab, Samsung J7, Samsung Tab A, Galaxy S6

### Cause
After some analysis, I found that crash is originating from CollectionPageSerializer which is being registered into Gson type adapter and which in function deserialize calls the method Type#getTypeName() which is a default method added after Java 1.8

Also can we make gson variable in DefaultSerializer public so that while configuring the graph client we can replace these problematic TypeAdapters with the custom solution. Like in case of when XXX is not supported in simpleDateFormat then same can be replaced with joda-time as we already have that dependency. Similarly in this case as well usage of getTypeName() can be replace with getName() or getCannonicalName() as to avoid crash

**Comment by baywet** [comment] 2020-10-15 12:57
Hi @atulgpt 
Thanks for reaching out.
For reference, the character issue you mentioned #530
The use of the method https://github.com/microsoftgraph/msgraph-sdk-java/blob/cd580a42cbc58668b4776d8de350fd6de66c8a74/src/main/java/com/microsoft/graph/serializer/CollectionPageSerializer.java#L115
The documentation that states this method was introduced with Java 1.8 https://docs.oracle.com/javase/8/docs/api/java/lang/reflect/Type.html and default methods are a Java 8 concept https://www.javatpoint.com/java-default-methods.
Android 7 is API level 24 https://developer.android.com/studio/releases/platforms#7.0 which supports default methods https://stackoverflow.com/a/46873490/3808675.
The catch is that getTypeName was apparently added in API level 28 https://developer.android.com/reference/java/lang/reflect/Type#getTypeName()

What's your minSdkVersion, your targetSdkVersion and have you enabled desugaring?

**Comment by atulgpt** [comment] 2020-10-15 13:40
Hi @baywet I have just ran the sample app with coreLibraryDesugaringEnabled turned to true and still getting the crash _java.lang.NoSuchMethodError: No virtual method getTypeName()Ljava/lang/String; in class Ljava/lang/Class; or its super classes (declaration of 'java.lang.Class' appears in /system/framework/core-libart.jar)_ while accessing the line **AttachmentCollectionPage::class.java.typeName**

Desugaring only changes the client code and don't affect the OS framework code. And if the method is missing in OS framework then it will definitely crash. And in case of newer apis like stream or Future or JSR310 coreLibraryDesugaringEnabled adds similar methods that delegates to already present apis on the OS but I think right now typeOfT.getTypeName() is not supported in coreLibraryDesugaringEnabled

In my sample app. minSdkVersion 21, targetSdkVersion 29 and compileSdkVersion 29
Lib version used for coreLibraryDesugaringEnabled: 'com.android.tools:desugar_jdk_libs:1.0.10'

**Comment by baywet** [comment] 2020-10-16 13:53
Thanks for the additional details.
I think the problems we're experiencing so far are caused by the fact the SDK doesn't define clearly which API level it requires, and subsequently, we don't have any tooling in place to check for this.
I tabled #546 as part of the larger version 3 work. I'm going to leave this issue open for visibility now.

**Comment by baywet** [comment] 2020-11-17 18:33
@atulgpt Thanks for your patience on the matter.
At this point we're tentatively targeting API level 21 and work is still in progress.
Can I ask you to try core with the `feature/api-level-baseline` branch, and this service library with `feature/api-level-baseline` branch in your project to double check it solves this issue please?

**Comment by atulgpt** [comment] 2020-11-23 20:47
Hi, @baywet sure. Is there any snapshot build or steps to build these repo locally so that I can try these in my local device?

**Comment by baywet** [comment] 2020-11-23 21:11
cloning the repo and running `gradlew build` should git you a local version, we don't have a snapshot setup at the moment.

**Comment by baywet** [comment] 2020-12-07 13:52
Hi @atulgpt 
Any luck? What results did you get?

**Comment by atulgpt** [comment] 2020-12-07 15:21
Hi @baywet I tried building these libs but .gradlew build failed on feature/v3 branch of msgraph-sdk-java(I tried feature/v3 as I couldn't find feature/android-api-baseline)

**Comment by baywet** [comment] 2020-12-07 16:09
the PR has been merged and the branch deleted, so feature/v3 was the right branch to use.
Could you share more details about the fail you had when trying to build?

**Comment by atulgpt** [comment] 2020-12-07 17:34
In run of ./gradlew build
\> Task :javadoc FAILED

FAILURE: Build failed with an exception.

\* What went wrong:
Execution failed for task ':javadoc'.
\> Javadoc generation failed. Generated Javadoc options file (useful for troubleshooting): '/Users/atulgup/Learning/MSGraph/modules/msgraph-sdk-java/build/tmp/javadoc/javadoc.options'

With stacktrace info, ./gradlew build --stacktrace
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':javadoc'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.lambda$executeIfValid$1(ExecuteActionsTaskExecuter.java:200)
        at org.gradle.internal.Try$Failure.ifSuccessfulOrElse(Try.java:263)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:198)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:179)
        at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:109)
        at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter.execute(ResolveTaskExecutionModeExecuter.java:62)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:57)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:56)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:36)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:77)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:55)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:52)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:200)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:195)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$3.execute(DefaultBuildOperationRunner.java:75)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$3.execute(DefaultBuildOperationRunner.java:68)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:153)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:68)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:62)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.lambda$call$2(DefaultBuildOperationExecutor.java:76)
        at org.gradle.internal.operations.UnmanagedBuildOperationWrapper.callWithUnmanagedSupport(UnmanagedBuildOperationWrapper.java:54)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:76)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:52)
        at org.gradle.execution.plan.LocalTaskNodeExecutor.execute(LocalTaskNodeExecutor.java:41)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:372)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:359)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:352)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:338)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.lambda$run$0(DefaultPlanExecutor.java:127)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:191)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.executeNextNode(DefaultPlanExecutor.java:182)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:124)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)

**It seems that javadoc task is failing**

My system Java version:
java version "1.8.0_231"
Java(TM) SE Runtime Environment (build 1.8.0_231-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.231-b11, mixed mode)

**Comment by baywet** [comment] 2020-12-07 18:19
I've (and the CI) been using these versions for a while now. It is possible for you to try under these versions?
```
openjdk 15 2020-09-15
OpenJDK Runtime Environment AdoptOpenJDK (build 15+36)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 15+36, mixed mode, sharing)
```

**Comment by baywet** [comment] 2020-12-08 15:47
I've just updated the CI to publish snapshots so it's easier for customers and partners to test these new versions:
In `build.gradle` add in the `repositories` block :
```
      jcenter {
                 url 'http://oss.jfrog.org/artifactory/oss-snapshot-local'
           }

And in the `dependencies` block replace the references to Microsoft graph and Microsoft graph core by:
 ```
api 'com.microsoft.graph:microsoft-graph-core:1.0.5-SNAPSHOT'
api 'com.microsoft.graph:microsoft-graph:2.4.1-SNAPSHOT'
```

**Comment by baywet** [comment] 2020-12-15 13:25
@atulgpt Are you still interested in testing this improvement? or should I go ahead and close the issue?

**Comment by atulgpt** [comment] 2020-12-15 22:46
@baywet I tried running using snapshot but my device was not working that is why could not test it. You can close the issue. If I find any new issue then I'll create one in Github

**Closed** 2020-12-16 12:24 UTC
Labels: Needs: Attention :wave:, bug, fixed
