### ISSUE TITLE
Call Record Serialisation Issue using v6 :  Dangling name: guest

### ISSUE THREAD

**Issue by priya2395** [microsoftgraph/msgraph-sdk-java#1930] opened 2024-04-11 05:37 UTC
### Expected behavior
Proper Serialisation of Call Record

### Actual behavior
Getting below Error:
Dangling name: guest

### Steps to reproduce the behavior

```java
  String toJson(final Parsable callRecord) {
        try (JsonSerializationWriter writer = new JsonSerializationWriter()) {
            // Writes the specified object value to the stream with an optional given key.
            writer.writeObjectValue(CommonStringUtils.EMPTY, callRecord);
            try (InputStream stream = writer.getSerializedContent()) {
                return new String(Compatibility.readAllBytes(stream), StandardCharsets.UTF_8);
            }
        } catch (final Exception e) {
            throw new IllegalStateException(e);
        }
    }
```

Sample Call Record:
```json
{
  "@odata.context": "https://graph.microsoft.com/v1.0/$metadata#communications/callRecords/$entity",
  "id": "066586f8-c8fd-4863-8fd7-3d64400cccf9",
  "version": 2,
  "type": "groupCall",
  "modalities": [
    "audio"
  ],
  "lastModifiedDateTime": "2024-04-10T11:54:46.8816123Z",
  "startDateTime": "2024-04-10T11:32:55.6174588Z",
  "endDateTime": "2024-04-10T11:37:00.1587306Z",
  "organizer": {
    "acsUser": null,
    "spoolUser": null,
    "phone": null,
    "guest": null,
    "encrypted": null,
    "onPremises": null,
    "acsApplicationInstance": null,
    "spoolApplicationInstance": null,
    "applicationInstance": null,
    "application": null,
    "device": null,
    "user": {
      "id": "b5408316-45ca-41f3-9524-6d3123514ab4",
      "displayName": "test",
      "tenantId": "ae12674b-ab6d-4eba-bae1-f9a80c9b0064"
    }
  },
  "participants": [
    {
      "user": null,
      "acsUser": null,
      "spoolUser": null,
      "phone": null,
      "guest": {
        "id": "051de8db829b488e82fbb86990e48667",
        "displayName": "Guest user",
        "tenantId": null
      },
      "encrypted": null,
      "onPremises": null,
      "acsApplicationInstance": null,
      "spoolApplicationInstance": null,
      "applicationInstance": null,
      "application": null,
      "device": null
    },
    {
      "acsUser": null,
      "spoolUser": null,
      "phone": null,
      "guest": null,
      "encrypted": null,
      "onPremises": null,
      "acsApplicationInstance": null,
      "spoolApplicationInstance": null,
      "applicationInstance": null,
      "application": null,
      "device": null,
      "user": {
        "id": "b5408316-45ca-41f3-9524-6d3123514ab4",
        "displayName": "test",
        "tenantId": "ae12674b-ab6d-4eba-bae1-f9a80c9b0064"
      }
    }
  ]
}
```

**Comment by Ndiritu** [comment] 2024-04-22 08:16
@priya2395 thank you for reporting this. Kindly share the version of the SDK you're using.

**Comment by Ndiritu** [comment] 2024-04-22 08:20
*Triage Notes*
`organizer` and `participants` are [IdentitySet](https://learn.microsoft.com/en-us/graph/api/resources/callrecords-callrecord?view=graph-rest-1.0#properties) objects but response doesn't contain the [`odata.type`](https://learn.microsoft.com/en-us/graph/api/callrecords-callrecord-get?view=graph-rest-1.0&tabs=http#response-1) to allow deserialization to a type that has the `guest` property. Generic `IdentitySet`s don't have a `guest` property.

Verifying that customer is using version of the SDK that handles untyped nodes before further debugging

**Comment by priya2395** [comment] 2024-04-22 08:28
I am using below kiota and ms graph versions:
kiota- 1.0.6
msgraph - 6.2.0

**Comment by Ndiritu** [comment] 2024-04-23 21:24
@priya2395 please upgrade to the latest version of the microsoft-graph package and let me know if this still happens.

**Comment by priya2395** [comment] 2024-04-30 13:29
@Ndiritu Its happening with latest version too as mentioned in https://github.com/microsoftgraph/msgraph-sdk-java/issues/1969

**Comment by Ndiritu** [comment] 2024-05-02 07:41
Thanks for confirming @priya2395. Closing this as a duplicate of #1969  and will update on both scenarios there.

**Closed by Ndiritu** 2024-05-02 07:41 UTC
Labels: Needs: Attention :wave:, area:serialization
