### ISSUE TITLE
By when  Microsoft Graph version 1.8+ will be ready to use and will be moved in master repository?

### ISSUE THREAD

**Issue by jagriti22** [microsoftgraph/msgraph-sdk-java#395] opened 2020-07-14 10:31 UTC
I am facing issues while using below fields of Event class.

Event event = new Event();
event.isOnlineMeeting = true;
event.onlineMeetingProvider = OnlineMeetingProviderType.TEAMS_FOR_BUSINESS;

**Comment by ddyett** [comment] 2020-07-16 19:45
1.8 should be on maven and bintray.  Can you clarify the issue you are seeing?

**Comment by ddyett** [comment] 2020-07-16 20:30
duplicate of #394

**Closed by ddyett** 2020-07-16 20:30 UTC
Labels: ToTriage

**Comment by jagriti22** [comment] 2020-07-17 10:00
Hi @ddyett  

Thanks for your response.
Actually,I was referring code from master branch of git repository  for MS Graph SDK Java i.e. [https://github.com/microsoftgraph/msgraph-sdk-java/tree/master]
Here I found  gradle dependency version  ' compile('com.microsoft.graph:microsoft-graph:1.5.+')' .

I simply want to assure that is dependency version 1.8  ready to use for production environment as it is not updated in master branch yet.??
